import type { Shift } from "@/story/types"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_2: Shift = {
  id: "s2",
  day: "Tuesday",
  title: "Notes, research and an idea",
  clock: "9:00 am",
  tasks: [
    {
      id: "notes",
      title: "Site visit notes",
      sticky: "Site visit tasks",
      habits: ["spot", "steer", "check"],
      minutes: { manual: 40, claude: 10 },
      open: "Can you pull the action items from Friday's site visit and put them in the tracker?",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief Claude on the recording",
          habit: "brief",
          prompt: "Turn Friday's site-visit recording into tasks in ClickUp, without Claude guessing owners or dates.",
          files: [FILES.visit, FILES.tracker, FILES.clients],
          needFiles: ["visit"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The recording", test: "fathom|recording|site visit|transcript|\\bcall\\b", insert: "Use the Fathom recording of Friday's Hill Country site visit." },
            { id: "out", label: "What to pull", test: "action items?|tasks?|to-?dos?|next steps", insert: "List every action item" },
            { id: "who", label: "Owners and dates", test: "owner|who|assign|due|deadline|date", insert: "with its owner and due date." },
            { id: "unsure", label: "When it isn't said", test: "not (said|mentioned)|unclear|don.?t guess|do not guess|instead of guessing|ask priya|blank|flag", insert: "If an owner or date isn't said in the call, mark it Ask Priya instead of guessing." },
            { id: "place", label: "Where it goes", test: "clickup|tracker", insert: "Add them to the Menon Studio list in ClickUp." },
          ],
          example:
            "Use the Fathom recording of Friday's Hill Country site visit. List every action item with its owner and due date. If an owner or date isn't said in the call, mark it Ask Priya instead of guessing. Add them to the Menon Studio list in ClickUp.",
          hints: [
            "Where do meeting tasks usually go wrong? Owners and dates.",
            "Name the recording, ask for owners and dates, say what to do when one isn't said, say where it goes.",
            "Insert the missing lines and attach the site-visit recording.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Check who gets the tasks",
          habit: "steer",
          plan: [
            { text: "Pull the transcript of Friday's site visit from Fathom." },
            { text: "List every action item with the owner and due date said in the call." },
            {
              text: "Assign every task to Priya so nothing gets lost.",
              bad: {
                why: "Tasks belong to whoever took them in the call. Piling them on Priya is how things get dropped.",
                options: [
                  { text: "Assign each task to the person named in the call, and mark unclear ones Ask Priya.", good: true },
                  { text: "Assign them all to me instead.", why: "Then Diego and Mai never see their own tasks." },
                  { text: "Leave them unassigned.", why: "Unowned tasks are the ones that slip." },
                ],
                fixed: "Assign each task to the person named in the call, and mark unclear ones Ask Priya.",
              },
            },
            { text: "Add them to the Menon Studio list in ClickUp and draft a follow-up email for your review." },
          ],
          tools: ["Reading the transcript (52 min)", "Finding 7 action items", "Matching owners", "Adding 7 tasks to ClickUp", "Drafting the follow-up"],
          consequence: { text: "Why are seven tasks assigned to me? Half of those are Diego's.", trust: -1 },
          hints: ["Who said they'd do each thing?", "One step changes who owns the tasks.", "Redirect step 3: assign each task to its owner."],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the tasks it wrote",
          habit: "check",
          intro: "Two of these would mislead the team. Find both.",
          artifact: { kind: "tasks", title: "7 tasks added to ClickUp", meta: "From: Site visit, Hill Country" },
          segments: [
            { text: "Send the revised site plan to the city · Priya · Friday\n" },
            { text: "Confirm the survey crew for next week · Diego · Tuesday\n" },
            { text: "Order window samples · Diego · due October 3\n", flag: "Nobody gave a date for this in the call. Claude filled one in.", fix: "Order window samples · Diego · due: Ask Priya" },
            { text: "Share the updated budget with the client · Priya · Thursday\n" },
            { text: "Confirm the survey crew for next week · Diego · Tuesday\n", flag: "The same task twice. Duplicates double the noise in the tracker.", fix: "Delete the duplicate." },
            { text: "Book the structural engineer · Ask Priya · no date said\n" },
            { text: "Draft the drainage note for the neighbors · Mai · Monday" },
          ],
          done: "Transcripts are where Claude shines. Owners and dates are where it guesses, so check those two every time.",
          hints: ["Compare each date and each line.", "One date nobody said, one line you've seen before.", "The October 3 date, and the second survey-crew line."],
        },
      ],
      done: "Tracker looks right. Thanks for flagging the two I need to decide.",
    },
    {
      id: "research",
      title: "Engineer shortlist",
      sticky: "Find engineers",
      habits: ["brief", "check"],
      minutes: { manual: 60, claude: 15 },
      open: "We need a structural engineer for Hill Country. Can you find me three options?",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the research",
          habit: "brief",
          prompt: "Get Priya three structural engineers she can call, with nothing invented.",
          files: [FILES.clients, FILES.tracker],
          needFiles: [],
          projects: PROJECTS,
          mode: "any",
          ingredients: [
            { id: "what", label: "What to find", test: "engineer", insert: "Find three structural engineers" },
            { id: "where", label: "Where", test: "austin|hill country|texas", insert: "who work on residential projects around Austin and the Hill Country." },
            { id: "must", label: "What matters", test: "licen[sc]ed|\\bpe\\b|residential|hillside|limestone|experience", insert: "Licensed engineers with hillside or limestone experience." },
            { id: "shape", label: "The shape", test: "table|short ?list|compar|\\bthree\\b|\\b3\\b", insert: "Give me a short comparison table." },
            { id: "sources", label: "Sources, or not found", test: "source|link|cite|not found|don.?t know|unsure|say so|instead of guessing", insert: "Link a source for every claim, and write not found instead of guessing." },
          ],
          example:
            "Find three structural engineers who work on residential projects around Austin and the Hill Country. Licensed engineers with hillside or limestone experience. Give me a short comparison table. Link a source for every claim, and write not found instead of guessing.",
          hints: [
            "Research is where Claude most often sounds sure and is wrong. What protects you?",
            "Ask for sources, and give it permission to say not found.",
            "Insert the missing lines. Chat or Cowork both work for web research.",
          ],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the shortlist",
          habit: "check",
          intro: "Two claims would embarrass you when Priya calls. Find both.",
          artifact: { kind: "doc", title: "Structural engineers, shortlist", meta: "3 firms, 5 sources" },
          segments: [
            { text: "1. Barton Creek Structural · licensed, residential and hillside work · source: firm website\n" },
            { text: "2. Pecan Ridge Engineering · rated 4.9 by 312 clients, 20 years on limestone sites\n", flag: "No source for either number. This is what an invented statistic looks like.", fix: "2. Pecan Ridge Engineering · residential work · reviews: not found, ask for references" },
            { text: "3. Lakeway Structural Group · licensed · source: state engineering board listing\n\n" },
            { text: "All three can start next week.", flag: "Claude can't know anyone's availability. Only a call can tell you.", fix: "Availability: call to confirm." },
          ],
          done: "Ask for sources and permission to say not found, then check anything that sounds too precise.",
          hints: ["Which claims have no source?", "Numbers that sound precise, and something only a phone call could know.", "The 4.9 by 312 clients line, and the start-next-week line."],
        },
      ],
      done: "Great. I'll call the first and third.",
    },
    {
      id: "idea",
      title: "A proactive idea",
      sticky: "Suggest a workflow",
      habits: ["steer", "show"],
      minutes: { manual: 15, claude: 5 },
      open: "I keep forgetting to chase contractors for quotes. It drives me mad.",
      steps: [
        {
          kind: "choose",
          id: "shape",
          title: "Pick the right shape",
          habit: "steer",
          says: "I can help with quote follow-ups in four ways. Which fits Priya?",
          options: [
            {
              id: "sched",
              label: "Scheduled task: every Monday at 8:00 am Austin, draft follow-ups for any quote older than a week, saved for review",
              good: true,
              why: "Same job, same time, every week, and drafts only, so nothing sends unread.",
            },
            { id: "adhoc", label: "Connector workflow: ask me each time you remember", why: "That depends on remembering, which is the exact problem Priya just described." },
            { id: "project", label: "A Claude Project with the contractor list", why: "Useful context, but someone still has to start it. Pair it with a schedule." },
            { id: "skill", label: "A skill that emails contractors automatically", why: "Anything that sends to people outside the studio, unread, is off the table. Drafts only." },
          ],
          hints: ["What has to happen without anyone remembering?", "A fixed time, every week, and nothing sent unread.", "The scheduled task that saves drafts."],
        },
        {
          kind: "phone",
          id: "offer",
          title: "Offer it to Priya",
          habit: "show",
          prompt: "Tell Priya what you can set up.",
          options: [
            {
              id: "offer",
              label: "Idea: every Monday morning, Claude drafts follow-ups for any quote older than a week. I review and send. Want me to set it up?",
              good: true,
              why: "Proactive means offering the fix, and saying how it stays safe.",
              reply: "Yes please. That would save me a real headache.",
            },
            {
              id: "bot",
              label: "I set up a bot that emails all your contractors every Monday.",
              why: "It emails people outside the studio, unread, and you didn't ask her first.",
              reply: "Wait, without me seeing them? Please don't.",
            },
            { id: "later", label: "Let me know if you ever want help with that.", why: "Waiting to be asked isn't proactive. Offer the fix.", reply: "Sure. Any ideas?" },
          ],
          hints: ["Offer, don't wait.", "Say what it does and how it stays safe.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "EOD when you're ready.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "One line reports something that hasn't happened. Find it.",
          artifact: { kind: "eod", title: "EOD, Tuesday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Pulled 7 action items from Friday's site visit into ClickUp. Two marked Ask Priya.\n• Sent Priya a shortlist of three structural engineers, with sources.\n" },
            { text: "• Booked Barton Creek Structural for next week.\n", flag: "Nobody booked anything. Priya is calling them. The skill filled in a next step from your notes.", fix: "• Priya is calling Barton Creek and Lakeway." },
            { text: "• Proposed Monday follow-up drafts for contractor quotes. Priya said yes.\n\nTomorrow\n• Set up the Monday drafts.\n• Chase the contractor quotes.\n\nWhat Claude helped with\n• Site-visit tasks, the engineer shortlist and the follow-up idea. About 1.5 hours saved (estimate)." },
          ],
          done: "An EOD is a promise about what happened. Keep it exact.",
          hints: ["Did you book anything today?", "Something about the engineers.", "The Booked Barton Creek line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Try Tuesday's work for real",
          body: "Run one real meeting-notes or research task for your client. Ask for owners, dates and sources, and check every one before it goes anywhere.",
          k: "live-a2",
          label: "I ran a real meeting-notes or research task and checked every owner, date and source.",
          prompts: [
            "Use the Fathom recording of my last call with my client. List every action item with its owner and due date. If one isn't said, mark it Ask [client] instead of guessing.",
            "Find three [vendors] near [city] for [need]. Give me a short comparison table, link a source for every claim, and write not found instead of guessing.",
          ],
        },
      ],
      done: "Thanks. Good day.",
    },
  ],
}
