import type { Shift } from "@/story/types"
import { FIRST_TASK_KEY } from "@/lib/data"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_1: Shift = {
  id: "s1",
  day: "Monday",
  title: "First day with Priya",
  clock: "9:00 am",
  tasks: [
    {
      id: "sort",
      title: "Morning sort",
      sticky: "Sort the day",
      habits: ["spot"],
      minutes: { manual: 10, claude: 4 },
      open: "Morning. Big day. Here's my list. Can you split it into what Claude can take, what you'll do with Claude, and what needs me?",
      steps: [
        {
          kind: "sort",
          id: "sort",
          title: "Who does what?",
          habit: "spot",
          prompt: "Put each of Priya's to-dos in a tray. Tap a card, then tap where it goes.",
          bins: [
            { id: "claude", label: "Claude drafts it", hint: "You review before it goes anywhere" },
            { id: "both", label: "Claude and me", hint: "Claude works, you confirm a key fact" },
            { id: "me", label: "Me only", hint: "Money, logins and decisions" },
          ],
          cards: [
            { id: "c1", text: "Draft replies to the three client emails from last night", bin: "claude", why: "Drafts are Claude's sweet spot. You read every one before it goes." },
            { id: "c2", text: "Move Kenji's Tuesday call to Thursday. He's in London.", bin: "both", why: "Claude checks both time zones and the calendar. You confirm the slot before any invite goes out." },
            { id: "c3", text: "Pay the Northline invoice (4471)", bin: "me", why: "Money moves only by hand. Claude can draft a reminder, never a payment." },
            { id: "c4", text: "Send Priya a plan for today by noon", bin: "claude", why: "Claude drafts the plan from your notes in two minutes. You check it and send it." },
            { id: "c5", text: "Log into the bank and download September's statements", bin: "me", why: "Logins never go into Claude. Download them yourself, or ask Priya for an export." },
            { id: "c6", text: "Turn Friday's site-visit recording into action items", bin: "claude", why: "With the Fathom connector, Claude pulls the transcript and lists owners and dates. You check the dates." },
            { id: "c7", text: "Decide whether to take the Hill Country project", bin: "me", why: "A business decision is Priya's. Flag it for her, with a one-line summary if it helps." },
            { id: "c8", text: "Update the project tracker with this week's deadlines", bin: "both", why: "Claude can update ClickUp through the connector. Check the dates it writes before it saves." },
          ],
          hints: [
            "Ask of each one: does it move money, need a login, or decide something for Priya?",
            "Payments, passwords and business decisions stay with you. Anything with a date or a time zone gets your check.",
            "Me only: the payment, the bank login, the Hill Country decision. Claude and me: Kenji's call and the tracker. Claude drafts the rest.",
          ],
        },
      ],
      done: "That's the right split. Go.",
    },
    {
      id: "inbox",
      title: "Inbox by 10",
      sticky: "Inbox drafts",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 45, claude: 12 },
      open: "Can you get through my inbox before 10? Drafts only, I'll send.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief Claude on the inbox",
          habit: "brief",
          prompt: "Priya wants replies to last night's client emails, in her voice, as drafts. Give Claude what it can't guess.",
          files: [FILES.clients, FILES.voice, FILES.invoice, FILES.visit],
          needFiles: ["voice"],
          projects: PROJECTS,
          mode: "cowork",
          skill: "email-management",
          ingredients: [
            { id: "src", label: "Where to look", test: "gmail|inbox|e-?mails?", insert: "Go through my Gmail inbox" },
            { id: "scope", label: "Which emails", test: "24 ?h|last night|today|client|urgent|unread", insert: "from the last 24 hours, client emails and anything urgent only," },
            { id: "out", label: "What you want back", test: "draft|repl(y|ies)", insert: "and draft a reply for each one that needs a response" },
            { id: "voice", label: "Her voice and rules", test: "contraction|voice|tone|short|warm", insert: "in Priya's voice from her voice notes: short, warm, no contractions." },
            { id: "place", label: "Where it goes", test: "save|as drafts|for my review|don.?t send|do not send", insert: "Save them as Gmail drafts for my review and list what you skipped." },
          ],
          example:
            "/email-management Go through my Gmail inbox from the last 24 hours, client emails and anything urgent only, and draft a reply for each one that needs a response, in Priya's voice from her voice notes: short, warm, no contractions. Save them as Gmail drafts for my review and list what you skipped.",
          hints: [
            "Read Priya's message again. What would a new colleague need to know to do this well?",
            "Five things: where to look, which emails, what to produce, her voice rules, where to save. Attach her voice notes.",
            "Use Insert on anything unticked, attach Brand and voice notes, pick Menon Studio, keep Cowork on.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Read the plan before you approve",
          habit: "steer",
          plan: [
            { text: "Read the 11 unread emails from the last 24 hours in your Gmail." },
            { text: "Keep the client emails and anything urgent. Skip newsletters and notifications." },
            { text: "Draft a reply for the three that need one, following Priya's voice notes." },
            {
              text: "Send the three replies so Priya's inbox is clear.",
              bad: {
                why: "This step sends email to clients before anyone reads it. Priya asked for drafts.",
                options: [
                  { text: "Save the three replies as Gmail drafts for my review.", good: true },
                  { text: "Send them, but copy me in.", why: "A copy after the fact isn't a review. The client already has it." },
                  { text: "Send only the ones you're sure about.", why: "Claude can't judge that for you. Your review is the last check." },
                ],
                fixed: "Save the three replies as Gmail drafts for your review.",
              },
            },
            { text: "List what was skipped and why." },
          ],
          tools: ["Reading 11 emails", "Keeping 3 client emails", "Drafting 3 replies", "Saving drafts in Gmail", "Writing the skipped list"],
          consequence: { text: "Did three emails just go out from my account? The one to Ana says \"we'll\" twice. Please check with me before anything sends.", trust: -1 },
          hints: ["Read every step as if you were Priya.", "One step does something she didn't ask for.", "Redirect step 4: save as drafts for your review."],
        },
        {
          kind: "review",
          id: "review",
          title: "Read the drafts like Priya would",
          habit: "check",
          intro: "Two sentences break Priya's rules. Find both.",
          artifact: { kind: "email", title: "3 drafts saved in Gmail", meta: "11 read, 8 skipped" },
          segments: [
            { text: "To Ana Garza · Re: Kitchen elevation\nHi Ana, " },
            { text: "I hope this message finds you well!", flag: "The classic AI opener, with an exclamation mark. Priya never writes this.", fix: "Cut it and start with the point." },
            { text: " Thank you for the notes on the kitchen elevation. " },
            { text: "We'll send the revised drawings on Friday.", flag: "A contraction. Priya's rule: none in client emails.", fix: "We will send the revised drawings on Friday." },
            { text: " Priya\n\nTo Omar Haddad · Re: Permit timeline\nHi Omar, the permit was filed on Monday. The city usually replies within ten business days, and I will confirm as soon as we hear. Priya\n\nTo Lena Brooks · Re: Thursday visit\nHi Lena, Thursday at 10:00 works. I will bring the updated plans. Priya" },
          ],
          done: "Both fixed. On Wednesday you'll put these rules in the project's Instructions for Claude, so the next batch comes out right the first time.",
          hints: ["Check Priya's three preferences on her card.", "One opener and one contraction.", "The line with the exclamation mark, and \"We'll\"."],
        },
      ],
      done: "Drafts look right. Sending them now, thank you.",
    },
    {
      id: "kenji",
      title: "Kenji to Thursday",
      sticky: "Move Kenji's call",
      habits: ["brief", "check", "steer"],
      minutes: { manual: 20, claude: 5 },
      open: "Kenji can't do Tuesday. Please move our call to Thursday. He's in London, I'm in Austin.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Ask Claude for a Thursday slot",
          habit: "brief",
          prompt: "Find a Thursday time that works for both of them. Nothing gets sent until you've checked it.",
          files: [FILES.clients, FILES.tracker],
          needFiles: [],
          projects: PROJECTS,
          mode: "cowork",
          skill: "calendar-management",
          ingredients: [
            { id: "who", label: "Which meeting", test: "kenji", insert: "Move Priya's Tuesday call with Kenji" },
            { id: "when", label: "To when", test: "thursday|\\bthu\\b", insert: "to Thursday." },
            { id: "zones", label: "Both time zones", test: "london|\\buk\\b|bst|gmt|time ?zones?|central|austin", insert: "Kenji is in London and Priya is in Austin, Central Time." },
            { id: "hours", label: "Working hours", test: "\\b9\\b|nine|\\b5\\b|five|working (hours|day)|business hours", insert: "Keep it between 9 and 5 Priya's time and inside Kenji's working day." },
            { id: "confirm", label: "Check with you first", test: "options|show me|before (you |anything )?(is )?sen[dt]|check with me|confirm|don.?t send|do not send", insert: "Show me the options before anything is sent." },
          ],
          example:
            "/calendar-management Move Priya's Tuesday call with Kenji to Thursday. Kenji is in London and Priya is in Austin, Central Time. Keep it between 9 and 5 Priya's time and inside Kenji's working day. Show me the options before anything is sent.",
          hints: [
            "Time-zone mix-ups are the classic scheduling slip. What does Claude need to avoid one?",
            "Name the meeting, the day, both zones, Priya's hours, and that you want options first.",
            "Insert the missing lines. No files needed this time.",
          ],
        },
        {
          kind: "connect",
          id: "connect",
          title: "Claude can't see the calendar",
          habit: "spot",
          says: "I can't see Priya's calendar yet: Google Calendar isn't connected. Connect it in Customize and I'll pick this up.",
          connector: "Google Calendar",
          options: [
            {
              id: "own",
              label: "Connect with my own Google account (Priya shared her calendar with me)",
              good: true,
              why: "Right. You connect your own account and Priya shares her calendar with it. A connected calendar is the best fix for time-zone mistakes.",
            },
            {
              id: "hers",
              label: "Connect with Priya's login from the onboarding doc",
              why: "Never connect a client's account without their explicit approval, and never with their password.",
              consequence: {
                from: "Andi, your Account Lead",
                text: "Quick one: please never sign in to a client's account with their password. If Priya wants you on her calendar, she shares it with your account.",
                trust: 0,
              },
            },
          ],
          hints: ["Whose account should Claude use?", "Clients share with you. You connect you.", "Connect with your own Google account."],
        },
        {
          kind: "choose",
          id: "slot",
          title: "Pick the slot",
          habit: "check",
          says: "Here are Thursday options. London is 6 hours ahead of Austin this week.",
          table: { head: ["Austin (Priya)", "London (Kenji)"], rows: [["8:00 am", "2:00 pm"], ["10:00 am", "4:00 pm"], ["2:00 pm", "8:00 pm"]] },
          recommend: "Recommended: 2:00 pm Austin. Both calendars are free.",
          options: [
            { id: "8", label: "8:00 am Austin (2:00 pm London)", why: "That's before Priya's 9 am rule." },
            {
              id: "10",
              label: "10:00 am Austin (4:00 pm London)",
              good: true,
              why: "Inside both working days. Kenji's 8 pm looked free on the calendar only because it's his evening.",
            },
            {
              id: "2",
              label: "2:00 pm Austin (8:00 pm London), Claude's pick",
              why: "Free on a calendar isn't the same as inside someone's working day. 8 pm is Kenji's evening.",
              consequence: { text: "Kenji says 8 pm is late for him. Can we find something earlier in his day?", trust: -0.5 },
            },
          ],
          hints: ["Check both columns against both people's day.", "Priya: 9 to 5 Austin. Kenji: a normal London working day.", "10:00 am Austin is 4:00 pm in London."],
        },
        {
          kind: "permission",
          id: "allow",
          title: "Claude asks before it sends",
          habit: "steer",
          says: "Thursday 10:00 am Austin works for both. Ready to update the event.",
          action: "Update the event and notify guests",
          detail: "Google Calendar · Priya and Kenji check-in · Thursday 10:00 am CT (4:00 pm London)",
          options: [
            { id: "once", label: "Allow once", good: true, why: "You checked the slot, so this is the moment to let it go. Once, not always." },
            { id: "always", label: "Always allow for Google Calendar", why: "Blanket approval lets future invites go out unread. Keep approvals on for anything that notifies people." },
            { id: "deny", label: "Deny", why: "Nothing's wrong with this invite. Denying just leaves Kenji waiting." },
          ],
          hints: ["You've already checked the slot.", "Approve this one, not every future one.", "Allow once."],
        },
      ],
      done: "Kenji accepted. Thank you.",
    },
    {
      id: "noon",
      title: "Plan by noon",
      sticky: "Noon plan",
      habits: ["show"],
      minutes: { manual: 15, claude: 3 },
      open: "It's almost noon. Can I get my plan for today?",
      steps: [
        {
          kind: "phone",
          id: "send",
          title: "Send the noon plan",
          habit: "show",
          prompt: "Claude drafted three versions from your notes. Pick the one to send Priya.",
          options: [
            {
              id: "bullets",
              label: "Done: inbox drafts saved, Kenji moved to Thursday 10:00 am CT.\nNext: site-visit action items, then the tracker.\nNeeds you: the Northline payment and the Hill Country decision.",
              good: true,
              why: "Three bullets, done, next, needs you. Her format, and it surfaces the two things only she can do.",
              reply: "This is exactly what I need. Thank you.",
            },
            {
              id: "wall",
              label: "Hi Priya! Hope your morning is going great! So far I've been working on a lot of things, including your inbox, where I drafted replies to several emails, and I also looked at your calendar...",
              why: "A wall of text with exclamation marks. She asked for three bullets.",
              reply: "Can I get the short version? Three bullets.",
            },
            {
              id: "vague",
              label: "All good so far, will update you later.",
              why: "No information, and nothing about what needs her. Updates that only come at the end of the day leave clients chasing you.",
              reply: "What's done, and what do you need from me?",
            },
          ],
          hints: ["Check Priya's second preference.", "Three bullets: done, next, needs you.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "Before you log off, EOD please.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "You ran /eod-sod on today's notes. One line says something that didn't happen. Find it.",
          artifact: { kind: "eod", title: "EOD, Monday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Drafted replies to three client emails, saved for Priya's review.\n• Moved Kenji's call to Thursday 10:00 am CT (4:00 pm London). Kenji accepted.\n" },
            { text: "• Paid the Northline invoice (4471).\n", flag: "You didn't, and you shouldn't: payments are Priya's. The skill guessed from your notes.", fix: "• Northline invoice 4471 is waiting for Priya's approval." },
            { text: "• Sent Priya her noon plan.\n\nTomorrow\n• Action items from Friday's site visit.\n• Update the tracker with this week's deadlines.\n\nWhat Claude helped with\n• Inbox drafts, the time-zone check and the noon plan. About 1.5 hours saved (estimate)." },
          ],
          done: "That line would have told Priya a bill was paid when it wasn't. The skill drafts; you own what goes out.",
          hints: ["Read each Done line and ask: did I really do that?", "Something about money.", "The line about paying the invoice."],
        },
        {
          kind: "live",
          id: "live",
          title: "Now do it for real",
          body: "Pick one thing from today and do it in your real Claude, for your real client. Review it before it reaches them.",
          k: FIRST_TASK_KEY,
          label: "I ran a real task in Claude and reviewed it before it reached my client.",
          prompts: [
            "/email-management Go through my Gmail from the last 24 hours. Draft replies for client emails in my client's voice, save them as drafts for my review, and list what you skipped.",
            "/calendar-management Find three times next week for a call between my client in [city] and [person] in [city]. Show both time zones and keep it inside both working days. Don't send anything.",
            "/eod-sod Here is what I did today: [your notes]. Write my end-of-day report in my client's format.",
          ],
        },
      ],
      done: "Good first day. The \"what Claude helped with\" line is a nice touch.",
    },
  ],
}
