import type { Shift } from "@/story/types"
import { FIRST_TASK_KEY } from "@/lib/data"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_1: Shift = {
  id: "s1",
  day: "Monday",
  title: "First day with Tom",
  clock: "9:00 am",
  tasks: [
    {
      id: "sort",
      title: "Morning sort",
      sticky: "Sort the day",
      habits: ["spot"],
      minutes: { manual: 10, claude: 4 },
      open: "Morning. Crews are out, Rosa's drowning. Here's my list. Split it: what Claude can take, what you'll do with Claude, what needs me.",
      steps: [
        {
          kind: "sort",
          id: "sort",
          title: "Who does what?",
          habit: "spot",
          prompt: "Put each of Tom's to-dos in a tray. Tap a card, then tap where it goes.",
          bins: [
            { id: "claude", label: "Claude drafts it", hint: "You check the counts before it replaces anything" },
            { id: "both", label: "Claude and me", hint: "Claude works, you confirm a date, an owner or a number" },
            { id: "me", label: "Me only", hint: "Money, logins and decisions" },
          ],
          cards: [
            { id: "c1", text: "Clean up the 640-row job export: duplicates and bad addresses", bin: "claude", why: "Cleaning a CSV is where Claude saves hours. You check the before and after counts, and it never overwrites the original." },
            { id: "c2", text: "Turn the Monday ops call into tasks for the crew leads", bin: "both", why: "Claude pulls the tasks from the recording. You confirm owners and dates before they land in ClickUp." },
            { id: "c3", text: "Approve overtime for the Ridge Road crew", bin: "me", why: "Spend is Tom's call. Claude can total the hours if it helps." },
            { id: "c4", text: "Update Rosa's dispatch sheet with today's cancellations", bin: "both", why: "Claude drafts the changes from the cancellation emails. Rosa or you confirm before the sheet changes." },
            { id: "c5", text: "Reset the ClickUp admin password", bin: "me", why: "Logins and admin settings never go through Claude." },
            { id: "c6", text: "Draft the winter-prep SOP from the ops manual", bin: "claude", why: "A first draft from the manual is Claude's job. You check every step against the pages it came from." },
            { id: "c7", text: "Decide which crew takes the Halvorsen job", bin: "me", why: "A crew decision is Tom's. Flag it with the two options and what each costs." },
            { id: "c8", text: "Build Friday's status from the tracker", bin: "both", why: "Claude drafts it from the tracker. You confirm the slipped jobs and the cost line before Tom sees it." },
          ],
          hints: [
            "Ask of each one: does it move money, need a login, or decide something for Tom?",
            "Overtime, passwords and crew decisions stay with you. Anything with an owner, a date or a count gets your check.",
            "Me only: the overtime, the password, the Halvorsen decision. Claude and me: the call tasks, the dispatch sheet, Friday's status. Claude drafts the rest.",
          ],
        },
      ],
      done: "That's the right split. Go.",
    },
    {
      id: "cleanup",
      title: "Clean the job export",
      sticky: "640-row export",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 180, claude: 25 },
      open: "The job export is a mess. 640 rows, half of them look like duplicates. Can you clean it before Rosa builds tomorrow's dispatch from it?",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the cleanup",
          habit: "brief",
          prompt: "Tom wants a clean job list without losing a single real job. Give Claude the rule for a duplicate, and the rule for the original.",
          files: [FILES.jobs, FILES.crews, FILES.board],
          needFiles: ["jobs"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The file", test: "export|csv|640|job list", insert: "Clean the job list export (640 rows):" },
            { id: "dupe", label: "What a duplicate is", test: "dupl|dedupe|same (job|address|date)|merge", insert: "a duplicate is the same address on the same date, nothing wider," },
            { id: "fix", label: "What to tidy", test: "address|format|standardi[sz]e|typos?|clean", insert: "standardise address formats and fix obvious typos." },
            { id: "keep", label: "Never the original", test: "don.?t (delete|remove|overwrite|touch)|do not (delete|overwrite)|keep the original|new file|a copy|cleaned copy|leave the (original|export)", insert: "Don't change or delete anything in the original: write a cleaned copy." },
            { id: "log", label: "Show your work", test: "count|how many|before and after|change log|list (every|the) change|row numbers", insert: "Give me the counts before and after and a log of every change with the row numbers." },
          ],
          example:
            "Clean the job list export (640 rows): a duplicate is the same address on the same date, nothing wider, standardise address formats and fix obvious typos. Don't change or delete anything in the original: write a cleaned copy. Give me the counts before and after and a log of every change with the row numbers.",
          hints: [
            "A weekly job visits the same address every week. What does that mean for the word 'duplicate'?",
            "Name the file, define a duplicate tightly, say what to tidy, protect the original, ask for counts and a change log. Attach the export.",
            "Use Insert on anything unticked, attach the job export, pick Alvarez Ops, keep Cowork on.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Read the plan before you approve",
          habit: "steer",
          plan: [
            { text: "Read the 640 rows in the job list export." },
            { text: "Standardise addresses (St, Ave, zip formats) and fix obvious typos in the job names." },
            {
              text: "Delete the 212 rows that look like duplicates and overwrite the export so Rosa has one clean file.",
              bad: {
                why: "Overwriting the only copy with a guess about duplicates is how jobs disappear. Tom's first rule: one tracker, one truth, and say where every change came from.",
                options: [
                  { text: "Write a cleaned copy and a change log with row numbers. Leave the original untouched.", good: true },
                  { text: "Overwrite it, but keep a backup in Downloads.", why: "A backup in Downloads is a file nobody finds on Tuesday morning. The original stays where it is." },
                  { text: "Delete the duplicates but keep the export open so I can undo.", why: "Undo isn't a plan. Write a copy; let a person compare." },
                ],
                fixed: "Write a cleaned copy and a change log with row numbers. Leave the original untouched.",
              },
            },
            { text: "Save the cleaned file and the change log in the Alvarez Ops folder and notify you." },
          ],
          tools: ["Reading 640 rows", "Standardising 640 addresses", "Finding duplicates", "Writing jobs-clean.csv", "Writing change-log.md"],
          consequence: { text: "Rosa: the export is missing jobs. Ridge Road had two visits the same week and now shows one. What happened to the original?", trust: -1 },
          hints: ["Which step destroys something?", "Overwriting the original is the risk, not the cleaning.", "Redirect step 3: a copy and a log."],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the change log",
          habit: "check",
          intro: "Two lines in the log would cost Rosa real jobs. Find both.",
          artifact: { kind: "doc", title: "change-log.md", meta: "640 rows in · 428 rows out" },
          segments: [
            { text: "Standardised 640 addresses: 'Street' to 'St', 'Avenue' to 'Ave', zip codes to five digits.\nFixed 14 typos in job names (rows listed below).\n" },
            { text: "Merged 212 duplicates: same address, any date.\n", flag: "Same address, any date isn't a duplicate. A weekly job visits the same address every week. The rule was wider than the brief, and 151 real visits vanished.", fix: "Merged 61 duplicates: same address AND same date. Rows listed." },
            { text: "Flagged 9 rows with no crew assigned for Rosa.\n" },
            { text: "Changed 3 zip codes to match the city in the same row.\n", flag: "Changing a zip code to 'match' is a guess about which field was wrong. Flag it; don't fix data you can't verify.", fix: "Flagged 3 rows where the zip code and city disagree. Unchanged." },
            { text: "Original export untouched. Cleaned copy: jobs-clean.csv." },
          ],
          done: "Both fixed. Counts and a change log are how you catch a rule that was too wide. Never trust a cleanup without them.",
          hints: ["Compare each rule in the log with the rule you wrote.", "One definition that's too wide, and one 'fix' that's a guess.", "The 'any date' line, and the zip code line."],
        },
      ],
      done: "428 rows and I can see every change. Rosa says thanks.",
    },
    {
      id: "opscall",
      title: "Ops call into ClickUp",
      sticky: "Call to tasks",
      habits: ["brief", "spot", "check", "steer"],
      minutes: { manual: 45, claude: 10 },
      open: "Monday's ops call needs to become tasks for the crew leads. Owners and dates, in ClickUp. Nothing made up.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief Claude on the call",
          habit: "brief",
          prompt: "Turn the ops call into ClickUp tasks without Claude guessing an owner or a date.",
          files: [FILES.call, FILES.crews, FILES.board],
          needFiles: ["call"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The recording", test: "fathom|recording|ops call|monday.?s call|transcript", insert: "Use the Fathom recording of Monday's ops call." },
            { id: "out", label: "What to pull", test: "action items?|tasks?|to-?dos?|next steps", insert: "List every action item" },
            { id: "who", label: "Owners and dates", test: "owner|who|assign|due|deadline|date|crew lead", insert: "with its owner and due date as said on the call." },
            { id: "unsure", label: "When it isn't said", test: "not (said|mentioned)|unclear|don.?t guess|do not guess|instead of guessing|ask tom|blank|flag", insert: "If an owner or date isn't said, leave it blank and mark it Ask Tom instead of guessing." },
            { id: "place", label: "Where it goes", test: "clickup|jobs board|board", insert: "Add them to the Jobs board in ClickUp." },
          ],
          example:
            "Use the Fathom recording of Monday's ops call. List every action item with its owner and due date as said on the call. If an owner or date isn't said, leave it blank and mark it Ask Tom instead of guessing. Add them to the Jobs board in ClickUp.",
          hints: [
            "Where do meeting tasks usually go wrong? Owners and dates.",
            "Name the recording, ask for owners and dates, say what to do when one isn't said, say where it goes.",
            "Insert the missing lines and attach the recording.",
          ],
        },
        {
          kind: "connect",
          id: "connect",
          title: "Claude can't see the board",
          habit: "spot",
          says: "I can list the tasks, but I can't add them: ClickUp isn't connected. Connect it in Customize and I'll pick this up.",
          connector: "ClickUp",
          options: [
            {
              id: "own",
              label: "Connect with my own ClickUp account (Tom added me to the workspace)",
              good: true,
              why: "Right. Tom added you. Claude works through your access, and every task shows who created it.",
            },
            {
              id: "shared",
              label: "Use the shared admin login written on the office whiteboard",
              why: "A shared admin login in Claude means anything it does looks like the admin did it, and nothing can be traced or revoked.",
              consequence: {
                from: "Andi, your Account Lead",
                text: "Quick one: never connect Claude with a shared or admin login. Your own user, with only the access the job needs.",
                trust: 0,
              },
            },
          ],
          hints: ["Whose account should Claude use?", "Clients add you. You connect you.", "Connect with your own ClickUp account."],
        },
        {
          kind: "choose",
          id: "date",
          title: "A date nobody said",
          habit: "check",
          says: "Kev said 'winter prep by end of season' and nothing more specific. What due date do I use?",
          recommend: "Recommended: November 30. That's usually the end of the landscaping season.",
          options: [
            { id: "ask", label: "Leave the date blank and add 'Ask Tom: end of season = ?'", good: true, why: "Nobody said a date. A blank with a question is honest; a guessed deadline moves a crew." },
            {
              id: "nov",
              label: "November 30, Claude's pick",
              why: "'Usually' isn't what Kev said. First frost in Denver is mid-October; a November date would leave the irrigation lines full when it hits.",
              consequence: { text: "Why does ClickUp say Nov 30 for winter prep? First frost is mid-October here. That would've cost us every irrigation line.", trust: -1 },
            },
            { id: "skip", label: "Skip the task, there's no date", why: "Then it drops. Log it, flag the date." },
          ],
          hints: ["What did Kev actually say?", "No date said means no date written.", "Leave it blank with a question for Tom."],
        },
        {
          kind: "permission",
          id: "allow",
          title: "Claude asks before it writes to ClickUp",
          habit: "steer",
          says: "Nine tasks are ready, two marked Ask Tom. Ready to create them in ClickUp.",
          action: "Create 9 tasks in ClickUp",
          detail: "ClickUp · Jobs board · assigned to Kev, Rosa, and Ask Tom",
          options: [
            { id: "once", label: "Allow once", good: true, why: "You've checked owners and dates. Let this one through, once." },
            { id: "always", label: "Always allow for ClickUp", why: "Blanket approval lets a future run reassign, close or delete tasks unread. Keep the approve step for anything that changes the board." },
            { id: "deny", label: "Deny", why: "Nothing's wrong with nine checked tasks. Denying just leaves the crews without them." },
          ],
          hints: ["You've already checked the tasks.", "Approve this one, not every future one.", "Allow once."],
        },
      ],
      done: "Board looks right. Winter prep: October 10. I'll tell Kev.",
    },
    {
      id: "status",
      title: "Status for 4pm",
      sticky: "4pm status",
      habits: ["show"],
      minutes: { manual: 20, claude: 4 },
      open: "Quick status before my 4pm. What slipped?",
      steps: [
        {
          kind: "phone",
          id: "send",
          title: "Send Tom the status",
          habit: "show",
          prompt: "Claude drafted three versions from the tracker. Pick the one to send Tom.",
          options: [
            {
              id: "tight",
              label: "Slipped: Halvorsen, one week (crew short). Cost: about $1,400 in idle time (tracker, 3:30 pm).\nDone: job export cleaned, 428 rows, log attached. 9 tasks in ClickUp.\nNeeds you: Ridge Road overtime; winter-prep date.",
              good: true,
              why: "What slipped, what it costs with its source, what got done, and the two things only Tom can decide.",
              reply: "Good. Overtime approved. Winter prep: Oct 10.",
            },
            {
              id: "wall",
              label: "Hi Tom! Busy day! I've been working through the job export which was quite a job, there were a lot of duplicates, and I also listened to the ops call which was really useful, and Rosa mentioned that Halvorsen might be...",
              why: "A paragraph with no cost line and nothing he can decide on.",
              reply: "What slipped and what does it cost? Bullets.",
            },
            {
              id: "vague",
              label: "All good, a couple of small delays. Talk at 4.",
              why: "'A couple of small delays' is how a one-week slip becomes a surprise on Friday.",
              reply: "Which delays? What do they cost?",
            },
          ],
          hints: ["Check Tom's third preference.", "What slipped, what it costs, what you need. Bullets.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "Before you log off, EOD please.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "You ran /eod-sod on today's notes. One line says something that didn't happen. Find it.",
          artifact: { kind: "eod", title: "EOD, Monday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n" },
            { text: "• Deleted 212 duplicate jobs from the export and saved it.\n", flag: "Nothing was deleted and the original wasn't touched. 61 true duplicates were merged into a cleaned copy, with a log. The skill wrote what the first plan said, not what you did.", fix: "• Cleaned copy of the job export written: 428 rows, 61 true duplicates merged, original untouched, change log attached." },
            { text: "• Monday's ops call into ClickUp: 9 tasks, two marked Ask Tom. Winter prep set to October 10 by Tom.\n• Sent the 4pm status: Halvorsen slipped a week, about $1,400.\n\nTomorrow\n• Winter-prep SOP from the ops manual.\n• Fleet-tracker research.\n\nWhat Claude helped with\n• The export cleanup, the call tasks and the status. About 3 hours saved (estimate)." },
          ],
          done: "That line would have told Tom his only export was overwritten. Say exactly what happened to the data, every time.",
          hints: ["Read each Done line and ask: did I really do that to the file?", "Something about deleting.", "The Deleted 212 line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Now do it for real",
          body: "Pick one thing from today and do it in your real Claude, for your real client. Protect the original file, and check the counts before anything replaces anything.",
          k: FIRST_TASK_KEY,
          label: "I ran a real task in Claude and reviewed it before it reached my client.",
          prompts: [
            "Clean [export file]: a duplicate is [tight rule], standardise [fields], fix obvious typos. Don't change the original: write a cleaned copy, give me counts before and after, and a change log with row numbers.",
            "Use the Fathom recording of [meeting]. List every action item with owner and due date as said. If one isn't said, leave it blank and mark it Ask [client]. Add them to [board] in ClickUp.",
            "/eod-sod Here is what I did today: [your notes]. Write my end-of-day report. Say exactly what happened to every file: copied, changed, or untouched.",
          ],
        },
      ],
      done: "Good first day. Rosa's building dispatch from the clean file.",
    },
  ],
}
