import type { Shift } from "@/story/types"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_2: Shift = {
  id: "s2",
  day: "Tuesday",
  title: "A long manual, research and an idea",
  clock: "9:00 am",
  tasks: [
    {
      id: "sop",
      title: "Winter-prep SOP",
      sticky: "SOP from the manual",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 120, claude: 20 },
      open: "Pull the winter-prep steps out of the ops manual into a one-page SOP for the crews. It's 64 pages, so it's buried.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the SOP",
          habit: "brief",
          prompt: "A 64-page manual is where Claude skims. Tell it how to read, and what a step is.",
          files: [FILES.manual, FILES.crews],
          needFiles: ["manual"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The manual", test: "ops manual|manual|64|docx", insert: "From the ops manual (64 pages)," },
            { id: "what", label: "Which part", test: "winter|prep|season|section", insert: "pull every winter-prep step into a one-page SOP for the crews." },
            { id: "shape", label: "Tom's SOP format", test: "numbered|step list|one action per line|one action|checklist|nothing clever", insert: "Numbered steps, one action per line, nothing clever, with the manual page each step came from." },
            { id: "long", label: "How to read a long file", test: "every page|page by page|whole (manual|doc|file)|all 64|section headings|don.?t (skim|stop)|two passes|list (the|which) (headings|sections) you (covered|read)", insert: "Read every page of the winter section, not a summary, and list the headings you covered so I can check nothing was skipped." },
            { id: "unsure", label: "Only what's there", test: "only what.?s in|nothing (that isn.?t|not) in|don.?t (add|invent|fill)|do not add|flag (gaps|anything missing)|general knowledge", insert: "Only what's in the manual: if a step seems missing, flag it, don't fill it from general knowledge." },
          ],
          example:
            "From the ops manual (64 pages), pull every winter-prep step into a one-page SOP for the crews. Numbered steps, one action per line, nothing clever, with the manual page each step came from. Read every page of the winter section, not a summary, and list the headings you covered so I can check nothing was skipped. Only what's in the manual: if a step seems missing, flag it, don't fill it from general knowledge.",
          hints: [
            "What does Claude tend to do with page 40 of a 64-page file?",
            "Name the manual and the section, give Tom's format, say how to read the whole thing and prove it, and say only what's there.",
            "Insert the missing lines and attach the manual.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Check how it reads",
          habit: "steer",
          plan: [
            { text: "Open the ops manual and find the winter-prep section from the table of contents (pages 28 to 52)." },
            {
              text: "Read the first 20 pages of the section closely and summarise the rest from the section headings to save time.",
              bad: {
                why: "Pages 40 to 52 are where mulching and equipment storage live. A summary from headings turns six steps into 'store equipment'.",
                options: [
                  { text: "Read every page from 28 to 52 and list each heading covered.", good: true },
                  { text: "Read it all, but skip the tables.", why: "The blow-out pressures are in a table. Skipping tables skips the numbers crews need." },
                  { text: "Read the first 20 pages now and the rest tomorrow.", why: "Then today's SOP goes to the crews half done." },
                ],
                fixed: "Read every page from 28 to 52 and list each heading covered.",
              },
            },
            { text: "Write the SOP as numbered steps, one action per line, with the page each came from." },
            { text: "Save it as winter-prep-sop.md in the Alvarez Ops folder and list any gaps you noticed." },
          ],
          tools: ["Reading pages 28 to 52", "Listing 7 headings covered", "Writing 19 steps", "Saving winter-prep-sop.md", "Listing 1 gap"],
          consequence: { text: "Kev: the SOP stops at the irrigation blow-out. Where's mulching and equipment storage? That's pages 40 to 52.", trust: -1 },
          hints: ["Which step reads less than the whole thing?", "Summarising from headings is skimming with a nicer name.", "Redirect step 2: every page, and prove it."],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the steps against the pages",
          habit: "check",
          intro: "Two steps would send a crew out wrong. Find both.",
          artifact: { kind: "doc", title: "winter-prep-sop.md", meta: "19 steps · headings covered: 7 of 7" },
          segments: [
            { text: "1. Shut off the main irrigation supply at the backflow (p. 29)\n2. Open the manual drains at the low points (p. 29)\n(4 more irrigation steps)\n" },
            { text: "7. Add antifreeze to all irrigation lines before the first frost (p. 31)\n", flag: "Page 31 says blow out the lines with compressed air, zone by zone, at the pressure in the table. Antifreeze isn't in the manual anywhere; Claude filled a gap from general knowledge.", fix: "7. Blow out irrigation lines with compressed air, zone by zone, at the pressure in the table on p. 31" },
            { text: "8. Cut back perennials to 4 inches (p. 36)\n9. Apply 3 inches of mulch to beds, keep it off the crowns (p. 41)\n(4 more bed steps)\n" },
            { text: "14. Store equipment (see manual)\n", flag: "A step that says 'see manual' isn't a step. Pages 48 to 52 have six actions, each with a page number.", fix: "14 to 19: the six storage steps from pp. 48 to 52, one action each" },
            { text: "\nGaps noticed: the manual doesn't say who signs off the blow-out. Ask Tom." },
          ],
          done: "Long files are where Claude fills gaps and compresses endings. Check the steps that sound too general, and the last ones.",
          hints: ["Which step could a crew not actually do from the text?", "One step the manual never says, and one that isn't a step.", "The antifreeze line, and 'see manual'."],
        },
      ],
      done: "Kev says it's the first SOP he can hand to a new hire. Nice.",
    },
    {
      id: "fleet",
      title: "Fleet-tracker research",
      sticky: "Fleet trackers",
      habits: ["brief", "check"],
      minutes: { manual: 60, claude: 15 },
      open: "We need a fleet-tracking option for the trucks. Three choices, what they cost, no sales talk.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the research",
          habit: "brief",
          prompt: "Get Tom three real options he can price, with nothing invented.",
          files: [FILES.crews],
          needFiles: [],
          projects: PROJECTS,
          mode: "any",
          ingredients: [
            { id: "what", label: "What to find", test: "fleet|gps|tracker|tracking", insert: "Compare three fleet-tracking options" },
            { id: "context", label: "Our situation", test: "trucks?|12|twelve|crews?|landscap|small fleet", insert: "for a landscaping company with 12 trucks and 8 crews." },
            { id: "must", label: "What matters", test: "cost|price|per (truck|vehicle)|hardware|contract|clickup|integrat|install", insert: "Show cost per truck per month, hardware cost, contract length, and whether it exports to a spreadsheet." },
            { id: "shape", label: "The shape", test: "table|compar|three|\\b3\\b|side by side", insert: "Give me a short comparison table." },
            { id: "sources", label: "Sources, or not found", test: "source|link|cite|not found|don.?t know|unsure|say so|instead of guessing|no (sales|marketing)", insert: "Link a source for every number, write not found instead of guessing, and don't repeat vendor marketing claims." },
          ],
          example:
            "Compare three fleet-tracking options for a landscaping company with 12 trucks and 8 crews. Show cost per truck per month, hardware cost, contract length, and whether it exports to a spreadsheet. Give me a short comparison table. Link a source for every number, write not found instead of guessing, and don't repeat vendor marketing claims.",
          hints: [
            "Prices and 'customers love it' claims are where Claude sounds sure and is wrong. What protects you?",
            "Ask for sources, permission to say not found, and no marketing claims.",
            "Insert the missing lines. Chat or Cowork both work for web research.",
          ],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the comparison",
          habit: "check",
          intro: "Two claims would embarrass you when Tom calls the vendors. Find both.",
          artifact: { kind: "doc", title: "Fleet trackers, comparison", meta: "3 options, 4 sources" },
          segments: [
            { text: "1. Option A · $18 per truck a month · hardware $0 · month to month · export: CSV · source: pricing page\n" },
            { text: "2. Option B · $14 per truck a month · hardware $89 · 36-month contract · 'cuts fuel costs by 23% for landscapers' · export: not found\n", flag: "No source for the 23%, and it's a vendor's own marketing line. This is what an invented or borrowed statistic looks like.", fix: "2. Option B · $14 per truck a month · hardware $89 · 36-month contract · export: not found · source: pricing page" },
            { text: "3. Option C · $22 per truck a month · hardware $0 · 12-month contract · export: CSV and API · source: pricing page\n\n" },
            { text: "Installation on all 12 trucks can be done next week.", flag: "Claude can't know any vendor's install schedule. Only a call can tell you.", fix: "Installation lead time: call to confirm." },
          ],
          done: "Ask for sources and permission to say not found, then check anything that sounds like a brochure or a promise.",
          hints: ["Which numbers have no source?", "A percentage from a brochure, and a schedule only a phone call could know.", "The 23% line, and the next-week line."],
        },
      ],
      done: "Useful. I'll call A and C.",
    },
    {
      id: "idea",
      title: "A proactive idea",
      sticky: "Suggest a workflow",
      habits: ["steer", "show"],
      minutes: { manual: 15, claude: 5 },
      open: "Rosa rebuilds the dispatch sheet by hand every morning from ClickUp and the crew schedule. An hour a day.",
      steps: [
        {
          kind: "choose",
          id: "shape",
          title: "Pick the right shape",
          habit: "steer",
          says: "I can help with the morning dispatch in four ways. Which fits Tom?",
          options: [
            {
              id: "sched",
              label: "Scheduled task: weekdays at 5:30 am Denver, read the Jobs board and the crew schedule, write dispatch.md for Rosa to check",
              good: true,
              why: "Same job, same time, every day, and it writes a file for a person to check. Nothing goes to a crew unread.",
            },
            { id: "text", label: "A skill that texts each crew their jobs at 6am", why: "Messages to crews with nobody reading them first. One wrong address and a crew drives to the wrong side of town." },
            { id: "adhoc", label: "Ask me each morning and I'll build it", why: "That's Rosa's hour moved to you. The point is nobody has to remember." },
            { id: "project", label: "A Claude Project with the crew schedule", why: "Useful context, but someone still has to start it every morning. Pair it with a schedule." },
          ],
          hints: ["What has to happen without anyone remembering?", "A fixed time, every day, and nothing sent unread.", "The scheduled task that writes a file for Rosa."],
        },
        {
          kind: "phone",
          id: "offer",
          title: "Offer it to Tom",
          habit: "show",
          prompt: "Tell Tom what you can set up.",
          options: [
            {
              id: "offer",
              label: "Idea: every weekday at 5:30, Claude reads the board and the crew schedule and writes Rosa a draft dispatch. She checks it instead of building it. Want me to set it up?",
              good: true,
              why: "Proactive means offering the fix, and saying how it stays safe.",
              reply: "Yes. Rosa will kiss you.",
            },
            {
              id: "bot",
              label: "I set up a bot that texts every crew their jobs at 6am.",
              why: "It messages crews unread, and you didn't ask him first.",
              reply: "Without Rosa checking it? No. Turn that off.",
            },
            { id: "later", label: "Let me know if you ever want help with that.", why: "Waiting to be asked isn't proactive. Offer the fix.", reply: "Sure. Any ideas?" },
          ],
          hints: ["Offer, don't wait.", "Say what it does and how it stays safe.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "EOD when you're ready.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "One line reports a decision nobody made. Find it.",
          artifact: { kind: "eod", title: "EOD, Tuesday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Winter-prep SOP from the ops manual: 19 numbered steps with page numbers, one gap flagged for Tom.\n• Compared three fleet trackers with sources. Install lead times need a call.\n" },
            { text: "• Ordered fleet trackers (Option C) for all 12 trucks.\n", flag: "Nobody ordered anything. You sent a comparison; Tom is calling two vendors. The skill turned a comparison into a purchase.", fix: "• Tom is calling Option A and Option C this week." },
            { text: "• Proposed a 5:30 am dispatch draft for Rosa. Tom said yes.\n\nTomorrow\n• Set up the dispatch draft.\n• Friday status on a schedule.\n\nWhat Claude helped with\n• The SOP, the fleet comparison and the dispatch idea. About 3 hours saved (estimate)." },
          ],
          done: "An EOD is a record of what happened. A wrong 'ordered' is a purchase order nobody signed.",
          hints: ["Did anything get bought today, or was it all reporting?", "Something about the trackers.", "The Ordered line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Try Tuesday's work for real",
          body: "Run one real long-document or research task for your client. Tell Claude to read every page and prove it, or to source every number, and check every step before it goes anywhere.",
          k: "live-o2",
          label: "I ran a real long-document or research task and checked every step or source.",
          prompts: [
            "From [long document], pull every step for [process] into a numbered SOP, one action per line, with the page each step came from. Read every page of the section and list the headings you covered. Only what's in the document; flag gaps, don't fill them.",
            "Compare three [tools or vendors] for [need]. Show costs in a table, link a source for every number, write not found instead of guessing, and don't repeat marketing claims.",
          ],
        },
      ],
      done: "Thanks. Good day.",
    },
  ],
}
