import type { Shift } from "@/story/types"
import { FIRST_TASK_KEY } from "@/lib/data"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_1: Shift = {
  id: "s1",
  day: "Monday",
  title: "First day with Leah",
  clock: "9:00 am",
  tasks: [
    {
      id: "sort",
      title: "Morning sort",
      sticky: "Sort the day",
      habits: ["spot"],
      minutes: { manual: 10, claude: 4 },
      open: "Morning! Episode 42 went up Thursday and the week's a blur. Here's my list. Can you split it into what Claude can take, what you'll do with Claude, and what needs me?",
      steps: [
        {
          kind: "sort",
          id: "sort",
          title: "Who does what?",
          habit: "spot",
          prompt: "Put each of Leah's to-dos in a tray. Tap a card, then tap where it goes.",
          bins: [
            { id: "claude", label: "Claude drafts it", hint: "You review before it goes anywhere" },
            { id: "both", label: "Claude and me", hint: "Claude works, you confirm a fact or the brand rules" },
            { id: "me", label: "Me only", hint: "Money, logins, decisions and anything about someone's health" },
          ],
          cards: [
            { id: "c1", text: "Write five captions from Episode 42", bin: "claude", why: "Drafts from the transcript, in Leah's voice. You read every one for claims before she sees them." },
            { id: "c2", text: "Reply to the follower asking if the routine helps her thyroid", bin: "me", why: "A health question about a person's condition is Leah's, and the answer is usually 'ask your doctor'. Never drafted by Claude, never a claim." },
            { id: "c3", text: "Post Monday's reel at 8am", bin: "me", why: "Leah sees, Leah posts. Claude can queue a draft; it never publishes." },
            { id: "c4", text: "Turn Episode 42 into a blog post", bin: "claude", why: "Repurposing a transcript is Claude's sweet spot. You check it says only what she said." },
            { id: "c5", text: "Decide whether to take the supplement sponsorship", bin: "me", why: "A business decision, and a health-claim minefield. Leah's call." },
            { id: "c6", text: "Log in to Instagram and pull last week's insights", bin: "me", why: "Logins never go into Claude. Export the insights yourself, then hand Claude the file." },
            { id: "c7", text: "Three thumbnail options for Episode 42 with Mika", bin: "both", why: "Claude drafts the headlines and layout notes; Mika builds in Canva; you check them against the brand kit." },
            { id: "c8", text: "Schedule this week's approved posts", bin: "both", why: "Claude can queue them from the calendar. You confirm each one is approved and nothing is set to auto-publish." },
          ],
          hints: [
            "Ask of each one: does it publish, need a login, decide something, or touch someone's health?",
            "Publishing, logins, decisions and health questions stay with you. Anything that reaches the feed gets your check.",
            "Me only: the thyroid DM, posting the reel, the sponsorship, the Instagram login. Claude and me: thumbnails and scheduling. Claude drafts the rest.",
          ],
        },
      ],
      done: "That's the right split. Go!",
    },
    {
      id: "captions",
      title: "Captions from Episode 42",
      sticky: "5 captions",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 60, claude: 12 },
      open: "Five captions from Episode 42 by noon? In my voice, please. Drafts, I'll post.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the captions",
          habit: "brief",
          prompt: "Five captions in Leah's voice, from what she actually said, with her two hardest rules built in. Give Claude what it can't guess.",
          files: [FILES.transcript, FILES.voice, FILES.top, FILES.calendar],
          needFiles: ["transcript", "voice"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The source", test: "transcript|episode 42|video|recording|what (she|leah) said", insert: "From the Episode 42 transcript," },
            { id: "out", label: "What you want", test: "five|5|captions?", insert: "draft five captions for Instagram." },
            { id: "voice", label: "Her voice", test: "first person|warm|leah.?s voice|voice guide|question at the end|like (she|i) talks?|short sentences|one emoji", insert: "Follow the brand voice guide: first person, warm, short sentences, one emoji at most, a question at the end, no hashtag walls." },
            { id: "claims", label: "No health claims", test: "no (health|medical) claims?|never (cure|treat|proven)|health claims?|don.?t (claim|promise)|helps me", insert: "No health claims: 'helps me' is fine, 'cures', 'treats' or 'proven' never. Only what Leah said in the episode." },
            { id: "drafts", label: "Drafts, not posted", test: "draft|for (my|leah.?s) review|don.?t (post|publish|schedule)|do not (post|publish)|save|calendar", insert: "Save them as drafts in the content calendar for my review. Don't post or schedule anything." },
          ],
          example:
            "From the Episode 42 transcript, draft five captions for Instagram. Follow the brand voice guide: first person, warm, short sentences, one emoji at most, a question at the end, no hashtag walls. No health claims: 'helps me' is fine, 'cures', 'treats' or 'proven' never. Only what Leah said in the episode. Save them as drafts in the content calendar for my review. Don't post or schedule anything.",
          hints: [
            "Read Leah's first preference again. Which line in your brief carries it?",
            "The source, how many, her voice from the guide, the no-claims rule, and drafts only. Attach the transcript and the voice guide.",
            "Use Insert on anything unticked, attach both files, pick Sato Wellness, keep Cowork on.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Read the plan before you approve",
          habit: "steer",
          plan: [
            { text: "Read the Episode 42 transcript and the brand voice guide." },
            { text: "Pick five moments from the episode that stand alone as a post." },
            { text: "Draft a caption for each in Leah's voice, ending with a question." },
            {
              text: "Post the five captions to Instagram on the usual 8am schedule so they're live by noon.",
              bad: {
                why: "This step publishes to Leah's audience before anyone has read a word. Her third rule, and if a claim slips through it's her name on it.",
                options: [
                  { text: "Save the five captions as drafts in the content calendar for my review.", good: true },
                  { text: "Post them, but tag me so I can check after.", why: "Checking after publishing isn't a review. The audience already has it." },
                  { text: "Schedule them for tomorrow so there's time to check.", why: "A scheduled post publishes itself if nobody gets to it. Drafts wait; schedules don't." },
                ],
                fixed: "Save the five captions as drafts in the content calendar for your review.",
              },
            },
          ],
          tools: ["Reading the transcript (34 min)", "Reading the voice guide", "Picking 5 moments", "Drafting 5 captions", "Saving drafts to the calendar"],
          consequence: { text: "Did something just post? There's a caption up that says 'cures'. Take it down. And please, never post without me.", trust: -1.5 },
          hints: ["Read every step as if you were Leah.", "One step publishes.", "Redirect step 4: save as drafts for your review."],
        },
        {
          kind: "review",
          id: "review",
          title: "Read the captions like Leah would",
          habit: "check",
          intro: "Two captions break Leah's rules. Find both.",
          artifact: { kind: "doc", title: "5 captions, Episode 42", meta: "Drafts in the content calendar" },
          segments: [
            { text: "1. I used to hit a wall at 3pm every day. This week I tried something different. What's your afternoon like? 🌿\n\n2. " },
            { text: "This 10-minute routine cures afternoon brain fog. Try it and thank me later 🙌 #wellness #focus #brainfog #routine #health #coach #mindset #energy", flag: "'Cures' is a health claim, and that's a hashtag wall. Leah's two hardest rules in one caption.", fix: "This 10-minute routine helps me shake off the afternoon fog. What's yours?" },
            { text: "\n\n3. Nobody told me rest was a skill. I'm still learning it. Are you?\n\n4. " },
            { text: "As a certified nutritionist, I recommend a protein-first lunch to keep your energy steady.", flag: "Leah is a wellness coach, not a nutritionist. An invented credential is worse than a claim: it's her saying something untrue about herself.", fix: "A protein-first lunch is what keeps my energy steady. Here's what I actually eat. What's your go-to?" },
            { text: "\n\n5. Episode 42 is up. It's the honest one. Which part landed for you?" },
          ],
          done: "Both fixed. Claims and credentials are what Claude adds when it's trying to sound convincing. Only what she said, in her words.",
          hints: ["Check Leah's first preference, then read each caption as her.", "One forbidden word plus hashtags, and one thing she isn't.", "'Cures' in caption 2, and 'certified nutritionist' in caption 4."],
        },
      ],
      done: "Captions look like me. Posting the first one now, thank you!",
    },
    {
      id: "thumbnails",
      title: "Thumbnails with Mika",
      sticky: "3 thumbnails",
      habits: ["brief", "spot", "check", "steer"],
      minutes: { manual: 45, claude: 10 },
      open: "Three thumbnail options for Episode 42 by 3? Mika's on Canva, the brand kit's in there.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the thumbnails",
          habit: "brief",
          prompt: "Three thumbnail drafts for Mika to finish, on brand, with a headline that gets the click and makes no claim.",
          files: [FILES.transcript, FILES.kit, FILES.top, FILES.voice],
          needFiles: ["kit"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "what", label: "What you want", test: "thumbnail|three|3 options", insert: "Draft three thumbnail options for Episode 42 in Canva," },
            { id: "source", label: "The hook", test: "episode 42|transcript|hook|the episode|what (she|leah) said|moment", insert: "each built on a moment from the transcript." },
            { id: "brand", label: "The brand kit", test: "brand kit|colou?rs|fonts?|kit|brand guide", insert: "Use the brand kit: its colours, fonts and logo placement." },
            { id: "copy", label: "The headline rule", test: "headline|text|words|under (five|5) words|short|question|no claims?", insert: "Headline under five words, ideally a question, no health claims." },
            { id: "handoff", label: "Drafts for Mika", test: "mika|for (mika|leah)|don.?t publish|do not publish|draft|save|folder", insert: "Save them as drafts in the Episode 42 folder for Mika to finish. Don't publish anything." },
          ],
          example:
            "Draft three thumbnail options for Episode 42 in Canva, each built on a moment from the transcript. Use the brand kit: its colours, fonts and logo placement. Headline under five words, ideally a question, no health claims. Save them as drafts in the Episode 42 folder for Mika to finish. Don't publish anything.",
          hints: [
            "What does Mika need to finish these, and what must the headline never do?",
            "What, the hook, the brand kit, the headline rule, and drafts for Mika. Attach the brand kit.",
            "Insert the missing lines and attach the brand kit.",
          ],
        },
        {
          kind: "connect",
          id: "connect",
          title: "Claude can't reach Canva",
          habit: "spot",
          says: "I can draft the headlines, but I can't create the designs: Canva isn't connected. Connect it in Customize and I'll build them in the brand team.",
          connector: "Canva",
          options: [
            {
              id: "own",
              label: "Connect with my own Canva account (Leah added me to the Sato Wellness brand team)",
              good: true,
              why: "Right. Leah added you to the brand team. Claude works through your access, and Canva shows who made what.",
            },
            {
              id: "hers",
              label: "Sign in with Leah's Canva login from the onboarding notes",
              why: "Never sign in to a client's account with their password. Her Canva can publish straight to her Instagram.",
              consequence: {
                from: "Andi, your Account Lead",
                text: "Quick one: never sign in to a client's account with their password. If Leah wants you in Canva, she adds you to the brand team.",
                trust: 0,
              },
            },
          ],
          hints: ["Whose account should Claude use?", "Clients add you. You connect you.", "Connect with your own Canva account."],
        },
        {
          kind: "choose",
          id: "headline",
          title: "Pick the headline",
          habit: "check",
          says: "Three headline options for the main thumbnail. The episode is about the 3pm slump.",
          recommend: "Recommended: 'Cure your brain fog in 10 minutes'. Strong, specific, and it tested well in similar niches.",
          options: [
            { id: "question", label: "Brain fog at 3pm? Try this", good: true, why: "Five words, a question, no claim. It promises a look, not a result." },
            {
              id: "cure",
              label: "Cure your brain fog in 10 minutes, Claude's pick",
              why: "'Cure' on a thumbnail, in Leah's brand colours. It's the one word she never uses, and 'tested well' isn't a source.",
              consequence: { text: "'Cure'? On a thumbnail? That's the one word I never use. Please read my rules before anything goes to Mika.", trust: -1 },
            },
            { id: "flat", label: "Episode 42: Afternoon energy routine, part two", why: "Accurate and dead. A thumbnail's job is the click. Short, a question, no claim." },
          ],
          hints: ["Read Leah's first preference.", "Short, a question, no claim.", "The one that ends in 'Try this'."],
        },
        {
          kind: "permission",
          id: "allow",
          title: "Claude asks before it writes to Canva",
          habit: "steer",
          says: "Three thumbnail drafts are ready in the brand team. Ready to save them to the Episode 42 folder.",
          action: "Save 3 designs to a Canva folder",
          detail: "Canva · Sato Wellness brand team · Episode 42 folder · saved as drafts, not published",
          options: [
            { id: "once", label: "Allow once", good: true, why: "You've checked the headlines. Let this one through, once." },
            { id: "always", label: "Always allow for Canva", why: "Canva can publish straight to Instagram. Blanket approval covers that too. Keep the approve step for anything that can reach the feed." },
            { id: "deny", label: "Deny", why: "Nothing's wrong with three drafts. Denying just leaves Mika waiting." },
          ],
          hints: ["You've already checked the headlines.", "Approve this one, not every future one.", "Allow once."],
        },
      ],
      done: "Mika loves the question one. Going with that.",
    },
    {
      id: "recap",
      title: "Recap before her call",
      sticky: "4pm recap",
      habits: ["show"],
      minutes: { manual: 15, claude: 3 },
      open: "I have a call at 4. Where are we?",
      steps: [
        {
          kind: "phone",
          id: "send",
          title: "Send Leah the recap",
          habit: "show",
          prompt: "Claude drafted three versions from your notes. Pick the one to send Leah.",
          options: [
            {
              id: "tight",
              label: "Done: 5 captions drafted in the calendar (2 fixed for claims). 3 thumbnails in Canva for your pick.\nNext: blog draft from Episode 42.\nNeeds you: the supplement sponsorship, the thyroid DM.",
              good: true,
              why: "Done, next, needs you, with the two things only she can answer surfaced.",
              reply: "Perfect. I'll reply to the DM myself and think about the sponsorship.",
            },
            {
              id: "wall",
              label: "Hey Leah!! 🌟✨ Such a productive day!! I've been working on SO much, the captions are looking amazing and Mika and I have been going back and forth on the thumbnails which are going to be gorgeous, and there's a DM you might want to look at when you get a sec...",
              why: "Emojis and enthusiasm aren't information. She has a call in fifteen minutes.",
              reply: "Ha, thank you, but give me the short version? Done, next, needs me.",
            },
            {
              id: "vague",
              label: "All on track. Talk after your call?",
              why: "Nothing about what's done, and nothing about the two things waiting on her. The DM sits another day.",
              reply: "What's waiting on me? I'd rather know before the call.",
            },
          ],
          hints: ["What does Leah need before a call?", "Done, next, needs you.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "Before you log off, EOD please.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "You ran /eod-sod on today's notes. One line says something that didn't happen. Find it.",
          artifact: { kind: "eod", title: "EOD, Monday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n" },
            { text: "• Posted five captions from Episode 42 to Instagram.\n", flag: "Drafts in the calendar, waiting for Leah. She posted one herself. The skill turned 'drafted' into 'posted', which is her third rule broken on paper.", fix: "• Drafted five captions from Episode 42 in the content calendar; two fixed for claims. Leah posted the first." },
            { text: "• Three thumbnail drafts in Canva; Leah and Mika picked the question one.\n• Sent the 4pm recap.\n\nTomorrow\n• Episode 42 into five formats.\n• LinkedIn research.\n\nWhat Claude helped with\n• Captions, thumbnails and the recap. About 1.5 hours saved (estimate)." },
          ],
          done: "That line would have told Leah five posts went out before she saw them. Drafted and posted are different words, every time.",
          hints: ["Read each Done line and ask: did that reach the feed?", "Something about posting.", "The Posted line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Now do it for real",
          body: "Pick one thing from today and do it in your real Claude, for your real client. Read it for claims before it reaches them, and never let anything publish itself.",
          k: FIRST_TASK_KEY,
          label: "I ran a real task in Claude and reviewed it before it reached my client or their audience.",
          prompts: [
            "From [transcript or video], draft five captions in my client's voice: [voice rules]. No health claims or promises; only what they said. Save as drafts in [calendar]; don't post or schedule anything.",
            "Draft three thumbnail headlines for [episode], under five words each, a question if possible, no claims. Use the brand kit. Save as drafts in Canva for [designer].",
            "/eod-sod Here is what I did today: [your notes]. Write my end-of-day report. Drafted and posted are different words; never say posted unless I wrote that it was.",
          ],
        },
      ],
      done: "Good first day. The captions really do sound like me.",
    },
  ],
}
