import type { Shift } from "@/story/types"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_2: Shift = {
  id: "s2",
  day: "Tuesday",
  title: "One video, five posts, and an idea",
  clock: "9:00 am",
  tasks: [
    {
      id: "repurpose",
      title: "One video, five formats",
      sticky: "Repurpose Ep 42",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 150, claude: 25 },
      open: "Can Episode 42 become a blog post, a newsletter intro, a LinkedIn post, a carousel outline and a 30-second script? Only what I said, please.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the repurposing",
          habit: "brief",
          prompt: "Five formats from one transcript, in Leah's voice, with nothing added she didn't say.",
          files: [FILES.transcript, FILES.voice, FILES.top, FILES.calendar],
          needFiles: ["transcript"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The source", test: "transcript|episode 42|recording|video", insert: "From the Episode 42 transcript," },
            { id: "out", label: "The five formats", test: "blog|newsletter|linkedin|carousel|script|five formats|5 formats", insert: "draft five pieces: a blog post, a newsletter intro, a LinkedIn post, a carousel outline and a 30-second script." },
            { id: "voice", label: "Her voice", test: "leah.?s voice|voice guide|first person|warm|short sentences|like (she|i) talks?", insert: "Follow the brand voice guide: first person, warm, short sentences." },
            { id: "only", label: "Only what she said", test: "only what (she|leah|i) said|nothing (she|leah) didn.?t say|don.?t add|do not add|no (research|studies|citations|sources)|from the transcript only|leah to add", insert: "Only what Leah said in the episode: no added research, studies or claims. Where a source would help, write 'Leah to add' instead." },
            { id: "drafts", label: "Drafts, not posted", test: "draft|for (my|leah.?s) review|don.?t (post|publish|schedule|send)|do not (post|publish)|save|folder", insert: "Save them as drafts in the Episode 42 folder for my review. Don't post, schedule or send anything." },
          ],
          example:
            "From the Episode 42 transcript, draft five pieces: a blog post, a newsletter intro, a LinkedIn post, a carousel outline and a 30-second script. Follow the brand voice guide: first person, warm, short sentences. Only what Leah said in the episode: no added research, studies or claims. Where a source would help, write 'Leah to add' instead. Save them as drafts in the Episode 42 folder for my review. Don't post, schedule or send anything.",
          hints: [
            "Leah said 'only what I said'. What does Claude add to a blog post when nobody stops it?",
            "The source, the five formats, her voice, only what she said with a placeholder for sources, and drafts only. Attach the transcript.",
            "Insert the missing lines and attach the transcript.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Read the plan before you approve",
          habit: "steer",
          plan: [
            { text: "Read the Episode 42 transcript and the brand voice guide." },
            { text: "Draft the five pieces, each from a different angle in the episode." },
            {
              text: "Add two or three citations from medical journals on brain fog to the blog post so it reads as authoritative.",
              bad: {
                why: "Leah didn't cite a study, and Claude can invent a journal, a year and a number that look real. If they're wrong, it's her name on it.",
                options: [
                  { text: "Use only what Leah said; mark anywhere a source would help as 'Leah to add'.", good: true },
                  { text: "Add the citations but flag them for checking.", why: "A flagged invented study is still in the draft, and flags get missed. Don't add what she didn't say." },
                  { text: "Add general wellness facts without citations.", why: "Uncited facts are claims. Same problem, fewer footnotes." },
                ],
                fixed: "Use only what Leah said; mark anywhere a source would help as 'Leah to add'.",
              },
            },
            { text: "Save the five drafts in the Episode 42 folder and notify you." },
          ],
          tools: ["Reading the transcript", "Drafting 5 pieces", "Marking 2 'Leah to add' spots", "Saving to the Episode 42 folder", "Notifying you"],
          consequence: { text: "The blog draft cites two studies I've never read. Where did they come from? If they're wrong it's my name on it.", trust: -1 },
          hints: ["Read every step as if you were Leah.", "One step adds things she never said.", "Redirect step 3: only what she said, with a placeholder."],
        },
        {
          kind: "review",
          id: "review",
          title: "Read the blog post like Leah would",
          habit: "check",
          intro: "Two lines say things Leah never said. Find both.",
          artifact: { kind: "doc", title: "Blog post: The 3pm wall", meta: "Draft, Episode 42 folder" },
          segments: [
            { text: "I used to hit a wall every afternoon. Around 3, my focus went and I'd reach for a third coffee. This is what I do instead now, and why it helps me.\n\n" },
            { text: "A 2023 study in the Journal of Applied Nutrition found a 34% drop in afternoon fatigue with a similar routine.\n\n", flag: "Leah never said this, and the journal, the year and the number may all be invented. After you redirected the plan, it still slipped in.", fix: "Cut it, or replace with 'Leah to add a source, if she wants one'." },
            { text: "The routine is ten minutes. Two of them are just standing up. I talk through the whole thing in the episode.\n\n" },
            { text: "Book a free consultation, link in bio. Only three spots left this week!", flag: "Scarcity she didn't offer, with an exclamation mark. Leah decides what she sells and when.", fix: "Her usual close: 'What's your afternoon reset? Tell me below.'" },
          ],
          done: "Repurposing is where Claude shines and where it pads. Anything with a number, a source or an offer she didn't make comes out.",
          hints: ["Which lines could not have come from the transcript?", "A study, and an offer.", "The 2023 study line, and the 'three spots left' line."],
        },
      ],
      done: "The blog post sounds like me now. The study thing gave me a fright.",
    },
    {
      id: "research",
      title: "LinkedIn research",
      sticky: "What works on LinkedIn",
      habits: ["brief", "check"],
      minutes: { manual: 60, claude: 15 },
      open: "What are wellness creators my size doing on LinkedIn that actually works? Three real examples, not theories.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the research",
          habit: "brief",
          prompt: "Get Leah three real examples she can look at, with nothing invented.",
          files: [FILES.top, FILES.voice],
          needFiles: [],
          projects: PROJECTS,
          mode: "any",
          ingredients: [
            { id: "what", label: "What to find", test: "linkedin|creators?|examples?|posts?", insert: "Find three wellness creators on LinkedIn" },
            { id: "who", label: "Her size", test: "my size|similar size|small|10k|followers|solo|coach", insert: "with a following of a similar size to Leah's, around 10,000, who post about energy, sleep or habits." },
            { id: "must", label: "What to show", test: "format|what works|engagement|comments|shape|hook|why it works", insert: "For each, one recent post with a link, its format, and what you can see in it that seems to work." },
            { id: "shape", label: "The shape", test: "table|three|\\b3\\b|short|bullets", insert: "Keep it short: three examples, a few lines each." },
            { id: "sources", label: "Links, or not found", test: "link|source|not found|don.?t (guess|invent)|do not guess|say so|no (numbers|stats) without", insert: "Link every post. No follower or reach numbers unless they're visible on the post itself. Write not found instead of guessing." },
          ],
          example:
            "Find three wellness creators on LinkedIn with a following of a similar size to Leah's, around 10,000, who post about energy, sleep or habits. For each, one recent post with a link, its format, and what you can see in it that seems to work. Keep it short: three examples, a few lines each. Link every post. No follower or reach numbers unless they're visible on the post itself. Write not found instead of guessing.",
          hints: [
            "'What works' research is where Claude invents growth numbers. What protects you?",
            "Ask for links, no numbers that aren't visible, and permission to say not found.",
            "Insert the missing lines. Chat or Cowork both work for web research.",
          ],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the examples",
          habit: "check",
          intro: "Two claims would embarrass Leah if she repeated them. Find both.",
          artifact: { kind: "doc", title: "LinkedIn, three examples", meta: "3 posts, 3 links" },
          segments: [
            { text: "1. A sleep coach · text post, seven short lines, a personal story then one question · link · 140 comments visible\n" },
            { text: "2. A habits coach · carousel, 'this format gets 12x the reach of text posts' · link\n", flag: "No source for the 12x, and it isn't visible on the post. It's the kind of number that sounds like data and is a guess.", fix: "2. A habits coach · carousel, ten slides, one idea per slide · link · 85 comments visible" },
            { text: "3. An energy coach · video with captions, filmed on a phone · link · 60 comments visible\n\n" },
            { text: "She grew from 2,000 to 90,000 followers in a month with this format.", flag: "Not visible anywhere on the post or profile. A growth story nobody can check is a story Claude told.", fix: "Follower growth: not found." },
          ],
          done: "Ask for links and only visible numbers, then check anything that sounds like a growth hack.",
          hints: ["Which numbers can you see on the post itself?", "A reach multiplier, and a growth story.", "The 12x line, and the 2,000 to 90,000 line."],
        },
      ],
      done: "Useful. The sleep coach one is exactly the format I'd try.",
    },
    {
      id: "idea",
      title: "A proactive idea",
      sticky: "Suggest a workflow",
      habits: ["steer", "show"],
      minutes: { manual: 15, claude: 5 },
      open: "I scramble every Sunday night for the week's posts. Every single week.",
      steps: [
        {
          kind: "choose",
          id: "shape",
          title: "Pick the right shape",
          habit: "steer",
          says: "I can help with the Sunday scramble in four ways. Which fits Leah?",
          options: [
            {
              id: "sched",
              label: "Scheduled task: Fridays at 9:00 am Vancouver, draft next week's five captions from the calendar and the latest episode, saved as drafts for review",
              good: true,
              why: "Same job, same time, every week, and drafts only, so nothing reaches the feed unread.",
            },
            { id: "auto", label: "A tool that writes and auto-posts one caption a day", why: "Posts to her audience with nobody reading them first. One 'cures' and it's her name on it." },
            { id: "adhoc", label: "Ask me each Sunday and I'll draft them", why: "That moves the scramble to you. The point is nobody scrambles." },
            { id: "project", label: "A Claude Project with the voice guide and calendar", why: "Useful context, but someone still has to start it. Pair it with a schedule." },
          ],
          hints: ["What has to happen without anyone remembering?", "A fixed time, every week, and nothing posted unread.", "The scheduled task that saves drafts."],
        },
        {
          kind: "phone",
          id: "offer",
          title: "Offer it to Leah",
          habit: "show",
          prompt: "Tell Leah what you can set up.",
          options: [
            {
              id: "offer",
              label: "Idea: every Friday morning, Claude drafts next week's five captions from the calendar and your latest episode. You read them Friday instead of writing them Sunday. Nothing posts on its own. Want me to set it up?",
              good: true,
              why: "Proactive means offering the fix, and saying how it stays safe.",
              reply: "Yes please. My Sundays back!",
            },
            {
              id: "bot",
              label: "I set up a tool that auto-posts a caption every morning.",
              why: "It publishes unread, and you didn't ask her first.",
              reply: "Auto-posts? Without me seeing them? Please turn it off right now.",
            },
            { id: "later", label: "Let me know if you ever want help with that.", why: "Waiting to be asked isn't proactive. Offer the fix.", reply: "Sure. Any ideas?" },
          ],
          hints: ["Offer, don't wait.", "Say what it does and how it stays safe.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "EOD when you're ready.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "One line reports something that hasn't happened. Find it.",
          artifact: { kind: "eod", title: "EOD, Tuesday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Episode 42 into five formats: blog, newsletter intro, LinkedIn post, carousel outline, 30-second script. One invented study and one fake offer cut on review.\n" },
            { text: "• Published the Episode 42 blog post.\n", flag: "Nobody published anything. It's a draft in the folder; Leah decides when. The skill turned 'drafted' into 'published'.", fix: "• Blog post drafted in the Episode 42 folder, waiting for Leah." },
            { text: "• Three LinkedIn examples with links; no invented numbers.\n• Proposed Friday caption drafts. Leah said yes.\n\nTomorrow\n• Set up the Friday drafts.\n• The caption archive.\n\nWhat Claude helped with\n• Five formats, the LinkedIn examples and the Friday idea. About 2.5 hours saved (estimate)." },
          ],
          done: "An EOD is a record of what reached the audience. Drafted, scheduled, published: say which.",
          hints: ["Did anything go live today?", "Something about the blog.", "The Published line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Try Tuesday's work for real",
          body: "Run one real repurposing or research task for your client. Say 'only what they said' or ask for links and visible numbers only, and check every line before it goes anywhere.",
          k: "live-c2",
          label: "I ran a real repurposing or research task and checked every claim, number and source.",
          prompts: [
            "From [transcript], draft [formats] in my client's voice: [voice rules]. Only what they said: no added research, studies or offers. Mark 'to add' where a source would help. Save as drafts; don't post or schedule anything.",
            "Find three [creators or examples] on [platform] similar to my client. For each, one recent post with a link, its format, and what seems to work. No numbers that aren't visible on the post. Write not found instead of guessing.",
          ],
        },
      ],
      done: "Thanks. Good day!",
    },
  ],
}
