import type { Shift } from "@/story/types"
import { FIRST_TASK_KEY } from "@/lib/data"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_1: Shift = {
  id: "s1",
  day: "Monday",
  title: "First day with Marco",
  clock: "9:00 am",
  tasks: [
    {
      id: "sort",
      title: "Morning sort",
      sticky: "Sort the day",
      habits: ["spot"],
      minutes: { manual: 10, claude: 4 },
      open: "Morning. Month-end is coming and my list is long. Can you split it into what Claude can take, what you'll do with Claude, and what needs me?",
      steps: [
        {
          kind: "sort",
          id: "sort",
          title: "Who does what?",
          habit: "spot",
          prompt: "Put each of Marco's to-dos in a tray. Tap a card, then tap where it goes.",
          bins: [
            { id: "claude", label: "Claude drafts it", hint: "You check it against the document before it goes anywhere" },
            { id: "both", label: "Claude and me", hint: "Claude works, you confirm a number or a match" },
            { id: "me", label: "Me only", hint: "Money, logins and decisions" },
          ],
          cards: [
            { id: "c1", text: "Type the 14 September supplier invoices into the tracker", bin: "claude", why: "PDFs into a sheet is where Claude saves hours. You check the totals against the PDFs." },
            { id: "c2", text: "Match last week's bank lines to invoices", bin: "both", why: "Claude matches and lists what doesn't fit. You confirm every exception before anything changes." },
            { id: "c3", text: "Pay the Bright Roast invoice, due today", bin: "me", why: "Money moves only by hand, and only by Marco. Claude can flag it, never pay it." },
            { id: "c4", text: "Draft reminders for the three overdue wholesale accounts", bin: "claude", why: "Reminders are drafts from the aging report. You read every one before it goes." },
            { id: "c5", text: "Log into the bank and add a new payee", bin: "me", why: "Logins never go into Claude. Bank admin is yours or Marco's." },
            { id: "c6", text: "Approve Sol's expense claim", bin: "me", why: "Approving spend is Marco's call. Claude can summarise the claim if it helps." },
            { id: "c7", text: "Categorise last week's uncategorised transactions in QuickBooks", bin: "both", why: "Claude suggests categories from the chart of accounts. You confirm before anything is written." },
            { id: "c8", text: "Build Friday's cash line from the bank export", bin: "both", why: "Claude drafts it from the export. You confirm the balance against the bank before Marco sees it." },
          ],
          hints: [
            "Ask of each one: does it move money, need a login, or decide something for Marco?",
            "Payments, logins and approvals stay with you. Anything with a number Marco will rely on gets your check.",
            "Me only: the payment, the bank login, the expense approval. Claude and me: the bank match, QuickBooks categories, the cash line. Claude drafts the rest.",
          ],
        },
      ],
      done: "That's the right split. Go.",
    },
    {
      id: "invoices",
      title: "Invoices into the tracker",
      sticky: "14 invoices",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 60, claude: 12 },
      open: "Fourteen supplier invoices for September are in the folder. Can you get them into the tracker before Dee asks?",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief Claude on the invoices",
          habit: "brief",
          prompt: "Marco wants every September invoice in the tracker, exactly as printed. Give Claude what it can't guess.",
          files: [FILES.invoices, FILES.tracker, FILES.chart, FILES.vendors],
          needFiles: ["invoices"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "Which documents", test: "14|fourteen|september|invoices? (folder|pdfs?)|pdfs?", insert: "Read the 14 supplier invoice PDFs in the September invoices folder" },
            { id: "out", label: "Where they go", test: "tracker|sheet|spreadsheet|xlsx|table|row", insert: "and add each one as a row in the invoice tracker:" },
            { id: "fields", label: "Which fields", test: "vendor|invoice number|due date|amount|total|tax", insert: "vendor, invoice number, invoice date, due date, amount before tax, tax and total." },
            { id: "blank", label: "When it isn't printed", test: "blank|not (printed|there|on the)|don.?t guess|do not guess|instead of guessing|ask me|leave it empty|list (it|them) for me", insert: "If a field isn't printed on the invoice, leave it blank and list it for me instead of guessing." },
            { id: "place", label: "Where it's saved", test: "save|for my review|ruiz coffee|books folder|don.?t (send|share)|do not send", insert: "Save the tracker in the Ruiz Coffee books folder for my review." },
          ],
          example:
            "Read the 14 supplier invoice PDFs in the September invoices folder and add each one as a row in the invoice tracker: vendor, invoice number, invoice date, due date, amount before tax, tax and total. If a field isn't printed on the invoice, leave it blank and list it for me instead of guessing. Save the tracker in the Ruiz Coffee books folder for my review.",
          hints: [
            "Read Marco's first preference again. What does Claude need to be told so it never fills a gap?",
            "Five things: which PDFs, where the rows go, which fields, what to do with a missing field, where to save. Attach the invoices.",
            "Use Insert on anything unticked, attach the September invoices, pick Ruiz Coffee books, keep Cowork on.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Read the plan before you approve",
          habit: "steer",
          plan: [
            { text: "Open the 14 PDFs in the September invoices folder." },
            { text: "Read vendor, invoice number, dates, amount, tax and total from each one." },
            {
              text: "Two invoices have no due date printed. Use 30 days from the invoice date so the column is complete.",
              bad: {
                why: "A due date Claude made up looks exactly like a real one in the tracker. Marco's rule: a blank beats a guess.",
                options: [
                  { text: "Leave the due date blank on both and list them for me.", good: true },
                  { text: "Use each vendor's terms from last month's invoices.", why: "Terms change, and last month isn't printed on this invoice. A wrong due date becomes a late fee." },
                  { text: "Put today's date so nothing is missed.", why: "Now two bills look overdue on day one, and Dee chases vendors for nothing." },
                ],
                fixed: "Leave the due date blank on both and list them for you.",
              },
            },
            { text: "Add the 14 rows to the tracker and total the month." },
          ],
          tools: ["Reading 14 PDFs", "Extracting 7 fields each", "Listing 2 missing due dates", "Adding 14 rows", "Totalling September"],
          consequence: { text: "Dee says two due dates in the tracker don't match the invoices. Where did 30 days come from?", trust: -1 },
          hints: ["Read every step as if you were Marco.", "One step fills in something that isn't on the paper.", "Redirect step 3: leave it blank and list it."],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the rows against the PDFs",
          habit: "check",
          intro: "Two rows would mislead Dee at month-end. Find both.",
          artifact: { kind: "doc", title: "Invoice tracker, September", meta: "14 rows added" },
          segments: [
            { text: "Bright Roast Coffee · INV-2291 · 2 Sep · due 2 Oct · $1,190.00 + $94.00 = $1,284.00\n" },
            { text: "Pacific Dairy · 8834 · 3 Sep · due 17 Sep · $3,820.00 + $305.00 = $4,125.00\n", flag: "The PDF says $412.50. A decimal point moved, and the tax moved with it. Totals are the first thing to check against the source.", fix: "Pacific Dairy · 8834 · 3 Sep · due 17 Sep · $382.00 + $30.50 = $412.50" },
            { text: "Alder Paper Goods · A-1177 · 5 Sep · due: blank (listed) · $640.00 + $0.00 = $640.00\nCascade Cups · 5502 · 9 Sep · due 9 Oct · $215.00 + $17.20 = $232.20\n(10 more rows)\n\n" },
            { text: "September total: $18,940.30 · 14 invoices · all due dates filled", flag: "Two due dates were blank on the invoices. If the summary says all filled, something was guessed after you redirected it. Check the two Claude listed.", fix: "September total: $15,227.80 · 14 invoices · 12 due dates from the invoices, 2 blank and listed for Marco" },
          ],
          done: "Both fixed. Every number in a tracker is a promise. Check the totals against the source, and treat 'all filled' as a warning, not a win.",
          hints: ["Compare each total with what a coffee shop would really pay a dairy.", "One decimal in the wrong place, and one summary line that contradicts your redirect.", "The Pacific Dairy total, and the 'all due dates filled' line."],
        },
      ],
      done: "Tracker looks right. Dee says thanks.",
    },
    {
      id: "reminders",
      title: "Overdue reminders",
      sticky: "Chase overdue",
      habits: ["brief", "spot", "check", "steer"],
      minutes: { manual: 30, claude: 8 },
      open: "Three wholesale accounts are overdue. Can you chase them? Nicely, they're good customers.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the reminders",
          habit: "brief",
          prompt: "Reminders for the overdue accounts, in Marco's voice, as drafts. Nothing invented, nothing sent.",
          files: [FILES.aging, FILES.template, FILES.vendors],
          needFiles: ["aging"],
          projects: PROJECTS,
          mode: "cowork",
          skill: "email-management",
          ingredients: [
            { id: "src", label: "Who is overdue", test: "overdue|aging|three|3 (accounts|customers)|wholesale", insert: "Using the overdue customer invoices sheet, draft a reminder for each of the three overdue wholesale accounts" },
            { id: "facts", label: "The facts from the sheet", test: "invoice number|amount|due date|from the sheet|as listed", insert: "with the invoice number, amount and due date exactly as listed." },
            { id: "voice", label: "His voice", test: "marco.?s voice|template|friendly|plain|short|no jargon|nicely|warm", insert: "Follow the reminder template: short, friendly, plain words, no late fees mentioned." },
            { id: "unsure", label: "When something's missing", test: "missing|not (in|on) the sheet|don.?t guess|do not guess|ask me|blank|flag", insert: "If an amount or date isn't on the sheet, ask me instead of guessing." },
            { id: "place", label: "Drafts, not sent", test: "draft|for my review|don.?t send|do not send|save", insert: "Save them as Gmail drafts for my review." },
          ],
          example:
            "/email-management Using the overdue customer invoices sheet, draft a reminder for each of the three overdue wholesale accounts with the invoice number, amount and due date exactly as listed. Follow the reminder template: short, friendly, plain words, no late fees mentioned. If an amount or date isn't on the sheet, ask me instead of guessing. Save them as Gmail drafts for my review.",
          hints: [
            "A reminder with a wrong amount costs more than no reminder. What stops that?",
            "Name the sheet, say the facts come from it, describe the tone, say what to do if a fact is missing, say drafts only.",
            "Insert the missing lines and attach the overdue sheet.",
          ],
        },
        {
          kind: "connect",
          id: "connect",
          title: "Claude can't see the invoice status",
          habit: "spot",
          says: "I can draft from the sheet, but I can't confirm whether any of these were paid since Friday: QuickBooks isn't connected. Connect it in Customize and I'll check before drafting.",
          connector: "QuickBooks",
          options: [
            {
              id: "own",
              label: "Connect with the read-only QuickBooks access Marco gave my account",
              good: true,
              why: "Right. Marco added your account as a read-only user. Claude checks payments through your access, and can't write anything.",
            },
            {
              id: "his",
              label: "Sign in with Marco's QuickBooks login from the handover doc",
              why: "Never sign in to a client's account with their password, and never give Claude an admin login to the books.",
              consequence: {
                from: "Andi, your Account Lead",
                text: "Quick one: never use a client's own login, and never connect Claude to the books with anything more than read-only access. Ask Marco for a user of your own.",
                trust: 0,
              },
            },
          ],
          hints: ["Whose access should Claude use, and how much?", "Your own user, read-only.", "Connect with the read-only access Marco gave you."],
        },
        {
          kind: "choose",
          id: "tone",
          title: "Who gets what",
          habit: "check",
          says: "QuickBooks shows three accounts still open. Here's what I see.",
          table: { head: ["Customer", "Overdue by", "Amount"], rows: [["Alder Bakery", "12 days", "$640.00"], ["Northgate Hotel", "41 days", "$3,120.00"], ["Fern & Co.", "3 days", "$215.00"]] },
          recommend: "Recommended: one firm reminder to all three, mentioning the late fee in the terms.",
          options: [
            {
              id: "split",
              label: "Friendly nudge to Alder and Fern. For Northgate, a note to Marco: 41 days is a phone call, not a template.",
              good: true,
              why: "Three days late is usually a bank delay. Forty-one days is a relationship problem, and that's Marco's call, not a reminder's.",
            },
            {
              id: "firm",
              label: "One firm reminder to all three, with the late fee, Claude's pick",
              why: "Fern is three days late, probably a transfer in flight. A late-fee note to a good wholesale account costs more than $215.",
              consequence: { text: "Fern just rang, upset about a late-fee email. They paid on Thursday. What happened?", trust: -1 },
            },
            { id: "skip", label: "Skip Fern, three days is nothing. Firm reminders to the other two.", why: "Northgate at 41 days needs Marco, not a firmer template. And a gentle nudge to Fern costs nothing." },
          ],
          hints: ["Read the days column like the customer would.", "Three days is a bank delay. Forty-one days is a conversation.", "Nudge the two small ones; hand Northgate to Marco."],
        },
        {
          kind: "permission",
          id: "allow",
          title: "Claude asks before it writes to Gmail",
          habit: "steer",
          says: "Two reminder drafts are ready, plus a note to Marco about Northgate. Ready to save them in Gmail.",
          action: "Create 2 drafts in Gmail",
          detail: "Gmail · To Alder Bakery and Fern & Co. · saved as drafts, not sent",
          options: [
            { id: "once", label: "Allow once", good: true, why: "You've checked the amounts and the tone. Let this one through, once." },
            { id: "always", label: "Always allow for Gmail", why: "Blanket approval for Gmail covers sending, not just drafting. Keep the approve step for anything that can leave the shop." },
            { id: "deny", label: "Deny", why: "Nothing's wrong with two drafts. Denying just leaves the accounts unchased." },
          ],
          hints: ["You've already checked the drafts.", "Approve this one, not every future one.", "Allow once."],
        },
      ],
      done: "Alder paid this morning. I'll ring Northgate myself.",
    },
    {
      id: "cash",
      title: "Cash line before the bank",
      sticky: "Cash line",
      habits: ["show"],
      minutes: { manual: 15, claude: 3 },
      open: "Quick one before my 2pm with the bank: where are we on cash?",
      steps: [
        {
          kind: "phone",
          id: "send",
          title: "Send Marco the number",
          habit: "show",
          prompt: "Claude drafted three versions from this morning's bank export. Pick the one to send Marco.",
          options: [
            {
              id: "line",
              label: "Cash: $22,410 across both accounts (bank export, 9:00 am today).\nOverdue in: $3,975 (3 accounts). Due out this week: $6,210 (5 bills).\nNeeds you: Bright Roast $1,284, due today.",
              good: true,
              why: "One line on cash with its source and time, what's owed in and out, and the one thing only Marco can do.",
              reply: "Perfect. That's what I'll say to the bank.",
            },
            {
              id: "wall",
              label: "Hi Marco! So I had a good look at everything this morning and overall cash seems pretty healthy. There are a few invoices we're waiting on, and a few bills coming up, but nothing too worrying, and...",
              why: "A paragraph with no figure in it, minutes before a bank meeting.",
              reply: "I need the number, not the weather.",
            },
            {
              id: "guess",
              label: "Roughly $25k I think, should be fine.",
              why: "'I think' on a cash number. Numbers come from a document, with the source and the time.",
              reply: "Where's that from? Give me the real figure.",
            },
          ],
          hints: ["Check Marco's second preference.", "One line, sourced, plus what's in, what's out, and what needs him.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "Before you log off, EOD please.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "You ran /eod-sod on today's notes. One line says something that didn't happen. Find it.",
          artifact: { kind: "eod", title: "EOD, Monday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Entered 14 September invoices in the tracker. Two due dates blank and listed for Marco. One total corrected against the PDF.\n• Drafted reminders for Alder and Fern; Northgate flagged for Marco to call.\n" },
            { text: "• Paid Bright Roast INV-2291, $1,284.00.\n", flag: "Nobody paid anything. Marco pays, and only Marco. The skill turned 'due today' into 'paid'.", fix: "• Bright Roast INV-2291, $1,284.00, due today. Flagged for Marco." },
            { text: "• Sent the cash line before the bank meeting.\n\nTomorrow\n• Match September's bank lines to the tracker.\n• Card-fee research.\n\nWhat Claude helped with\n• Invoice entry, reminder drafts and the cash line. About 1.5 hours saved (estimate)." },
          ],
          done: "That line would have told Marco a bill was paid when it wasn't. In bookkeeping, that's the worst kind of wrong.",
          hints: ["Read each Done line and ask: did I really do that?", "Something about money moving.", "The Paid Bright Roast line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Now do it for real",
          body: "Pick one thing from today and do it in your real Claude, for your real client. Check every number against the document before it reaches them.",
          k: FIRST_TASK_KEY,
          label: "I ran a real task in Claude and reviewed it before it reached my client.",
          prompts: [
            "Read the invoice PDFs in [folder] and add each one to [tracker]: vendor, invoice number, dates, amount, tax, total. If a field isn't printed, leave it blank and list it for me. Don't change existing rows.",
            "/email-management Using [overdue sheet], draft a friendly reminder for each overdue account with the invoice number, amount and due date exactly as listed. Save as Gmail drafts for my review.",
            "/eod-sod Here is what I did today: [your notes]. Write my end-of-day report. Never say something was paid unless I wrote that it was.",
          ],
        },
      ],
      done: "Good first day. Dee's happy, which is rare.",
    },
  ],
}
