import type { Shift } from "@/story/types"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_2: Shift = {
  id: "s2",
  day: "Tuesday",
  title: "Reconcile, research and an idea",
  clock: "9:00 am",
  tasks: [
    {
      id: "match",
      title: "Bank match",
      sticky: "Match the bank",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 90, claude: 20 },
      open: "Can you match September's bank lines to the invoices and tell me what doesn't add up? Don't fix anything, just tell me.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the reconciliation",
          habit: "brief",
          prompt: "Match the bank export to the tracker and surface every mismatch, without Claude touching a number.",
          files: [FILES.bank, FILES.tracker, FILES.chart],
          needFiles: ["bank"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The bank lines", test: "bank export|csv|september.?s bank|bank lines", insert: "Match every line in the September bank export" },
            { id: "against", label: "Against what", test: "tracker|invoices|invoice tracker", insert: "to the invoices in the tracker." },
            { id: "out", label: "What you want back", test: "list|flag|mismatch|doesn.?t (match|add up)|exceptions?|unmatched", insert: "List every line that doesn't match, with the bank figure and the tracker figure side by side." },
            { id: "noguess", label: "When it's unclear", test: "unclear|two (invoices|candidates)|don.?t (guess|pick|assume)|do not guess|ask me|flag it", insert: "If a bank line could match more than one invoice, don't pick: flag it for me." },
            { id: "nowrite", label: "Read only", test: "don.?t (change|edit|fix|touch|write)|do not (change|edit|fix)|read.?only|leave the tracker|no changes", insert: "Don't change the tracker or the export. Read only." },
          ],
          example:
            "Match every line in the September bank export to the invoices in the tracker. List every line that doesn't match, with the bank figure and the tracker figure side by side. If a bank line could match more than one invoice, don't pick: flag it for me. Don't change the tracker or the export. Read only.",
          hints: [
            "Marco said 'don't fix anything'. Which line in your brief says that?",
            "Name both files, ask for a side-by-side list, say what to do when two invoices could match, say read only.",
            "Insert the missing lines and attach the bank export.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Read the plan before you approve",
          habit: "steer",
          plan: [
            { text: "Read the 61 lines in the September bank export." },
            { text: "Match each line to an invoice in the tracker by amount, date and vendor." },
            {
              text: "Where an amount is off by a few dollars, adjust the tracker to match the bank so everything reconciles.",
              bad: {
                why: "Editing the tracker to make it 'reconcile' hides the mismatch instead of reporting it. Marco said don't fix anything.",
                options: [
                  { text: "List every mismatch with both figures and leave the tracker alone.", good: true },
                  { text: "Adjust only differences under $5.", why: "Small differences are bank fees or typos, and both need a human to say which. Report, don't edit." },
                  { text: "Adjust the bank export instead of the tracker.", why: "Editing the bank's record is worse. Neither file changes." },
                ],
                fixed: "List every mismatch with both figures and leave the tracker alone.",
              },
            },
            { text: "Write the exceptions list to the Ruiz Coffee books folder and notify you." },
          ],
          tools: ["Reading 61 bank lines", "Matching against 14 invoices and 47 other entries", "Finding 3 exceptions", "Writing exceptions.md", "Notifying you"],
          consequence: { text: "Dee: the tracker no longer matches the invoices. Did someone edit the amounts?", trust: -1 },
          hints: ["Which step changes a file?", "Reconciling means reporting, not editing.", "Redirect step 3: list, don't adjust."],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the exceptions",
          habit: "check",
          intro: "Two of these three would send Dee down the wrong path. Find both.",
          artifact: { kind: "doc", title: "Reconciliation, September", meta: "61 bank lines · 58 matched · 3 exceptions" },
          segments: [
            { text: "1. Bank $1,284.00 on 19 Sep, BRIGHT ROAST · matches INV-2291 and INV-2306 (same amount). " },
            { text: "Matched to INV-2291, the older one.\n", flag: "Two invoices, same amount, and Claude picked one. That's a guess in a tie. Marco or Dee says which was paid.", fix: "Two candidates, INV-2291 and INV-2306. Ask Marco which was paid." },
            { text: "2. Bank $89.00 on 22 Sep, SQ *ALDER BAKERY · no invoice · " },
            { text: "categorised as Office supplies.\n", flag: "A Square deposit from Alder Bakery is a customer paying, not you buying supplies. The category came from a pattern, not the document.", fix: "Customer payment from Alder Bakery, no matching invoice. Ask Marco." },
            { text: "3. Bank $2,000.00 on 30 Sep, TRANSFER · not an invoice, looks like a move between the two shop accounts · flagged for Dee." },
          ],
          done: "Reconciliation is where Claude is fastest and most confident. Ties and categories are where it guesses, so those two get your eyes every time.",
          hints: ["Which line made a choice nobody gave it?", "A tie it broke, and a category it invented.", "The INV-2291 pick, and Office supplies."],
        },
      ],
      done: "Three exceptions, all real. That used to take Dee a morning.",
    },
    {
      id: "fees",
      title: "Card-fee research",
      sticky: "Card fees",
      habits: ["brief", "check"],
      minutes: { manual: 60, claude: 15 },
      open: "Our card processing fees feel high. Can you find out what the alternatives would cost us?",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the research",
          habit: "brief",
          prompt: "Get Marco three real options he can compare, with nothing invented.",
          files: [FILES.bank, FILES.chart],
          needFiles: [],
          projects: PROJECTS,
          mode: "any",
          ingredients: [
            { id: "what", label: "What to compare", test: "card|payment|processor|processing|fees", insert: "Compare three card payment processors for a two-shop cafe" },
            { id: "context", label: "Our situation", test: "square|pos|two shops|volume|counter|in.?person|wholesale", insert: "that take in-person card payments at the counter and invoices for wholesale." },
            { id: "must", label: "What matters", test: "quickbooks|integrat|contract|monthly fee|per.?transaction|rate", insert: "Show the per-transaction rate, any monthly fee, contract length, and whether it connects to QuickBooks." },
            { id: "shape", label: "The shape", test: "table|compar|three|\\b3\\b|side by side", insert: "Give me a short comparison table." },
            { id: "sources", label: "Sources, or not found", test: "source|link|cite|not found|don.?t know|unsure|say so|instead of guessing|no (estimate|savings)", insert: "Link a source for every number, write not found instead of guessing, and don't estimate our savings: you don't have our volume." },
          ],
          example:
            "Compare three card payment processors for a two-shop cafe that take in-person card payments at the counter and invoices for wholesale. Show the per-transaction rate, any monthly fee, contract length, and whether it connects to QuickBooks. Give me a short comparison table. Link a source for every number, write not found instead of guessing, and don't estimate our savings: you don't have our volume.",
          hints: [
            "Rates and fees are exactly the numbers Claude sounds sure about and gets wrong. What protects you?",
            "Ask for sources, permission to say not found, and no savings estimate without the volume.",
            "Insert the missing lines. Chat or Cowork both work for web research.",
          ],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the comparison",
          habit: "check",
          intro: "Two claims would embarrass you when Marco calls the processors. Find both.",
          artifact: { kind: "doc", title: "Card processors, comparison", meta: "3 options, 4 sources" },
          segments: [
            { text: "1. Option A · 2.6% + 10c · no monthly fee · month to month · QuickBooks: yes · source: pricing page\n" },
            { text: "2. Option B · 1.9% + 10c · $29 a month · 'rated best for cafes by 2,400 owners' · QuickBooks: yes\n", flag: "No source for the rating or the 2,400. A number that precise with no link is what an invented statistic looks like.", fix: "2. Option B · 1.9% + 10c · $29 a month · reviews: not found · QuickBooks: yes · source: pricing page" },
            { text: "3. Option C · 2.3% + 5c · no monthly fee · 12-month contract · QuickBooks: not found · source: pricing page\n\n" },
            { text: "Switching to Option B would save Ruiz Coffee about $412 a month.", flag: "Claude doesn't have September's card volume. A savings figure with no working is a guess with a dollar sign on it.", fix: "Savings: needs September's card volume from the bank export. Ask Marco before estimating." },
          ],
          done: "Ask for sources and permission to say not found, then check anything that sounds precise, especially a savings number.",
          hints: ["Which numbers have no source?", "A rating nobody linked, and a saving nobody could calculate.", "The 2,400 owners line, and the $412 a month line."],
        },
      ],
      done: "Useful. I'll call A and B this week.",
    },
    {
      id: "idea",
      title: "A proactive idea",
      sticky: "Suggest a workflow",
      habits: ["steer", "show"],
      minutes: { manual: 15, claude: 5 },
      open: "I always find out an account is overdue when it's way overdue. It drives me mad.",
      steps: [
        {
          kind: "choose",
          id: "shape",
          title: "Pick the right shape",
          habit: "steer",
          says: "I can help with overdue accounts in four ways. Which fits Marco?",
          options: [
            {
              id: "sched",
              label: "Scheduled task: every Monday at 8:00 am Portland, read the aging report and draft reminders for anything over 7 days, saved for review",
              good: true,
              why: "Same job, same time, every week, and drafts only, so nothing goes to a customer unread.",
            },
            { id: "adhoc", label: "Ask me each time you notice something is late", why: "That depends on noticing, which is the exact problem Marco just described." },
            { id: "project", label: "A Claude Project with the customer list and terms", why: "Useful context, but someone still has to start it. Pair it with a schedule." },
            { id: "auto", label: "A skill that emails customers automatically when they're late", why: "Anything that sends to customers unread is off the table, and a wrong 'you're late' email is expensive. Drafts only." },
          ],
          hints: ["What has to happen without anyone remembering?", "A fixed time, every week, and nothing sent unread.", "The scheduled task that saves drafts."],
        },
        {
          kind: "phone",
          id: "offer",
          title: "Offer it to Marco",
          habit: "show",
          prompt: "Tell Marco what you can set up.",
          options: [
            {
              id: "offer",
              label: "Idea: every Monday morning, Claude reads the aging report and drafts reminders for anything over a week late. I check and send. Want me to set it up?",
              good: true,
              why: "Proactive means offering the fix, and saying how it stays safe.",
              reply: "Yes please. That's the one thing I never get to.",
            },
            {
              id: "bot",
              label: "I set up a bot that emails late customers every Monday.",
              why: "It emails customers unread, and you didn't ask him first.",
              reply: "Without me seeing them? No. Turn that off.",
            },
            { id: "later", label: "Let me know if you ever want help with that.", why: "Waiting to be asked isn't proactive. Offer the fix.", reply: "Sure. Any ideas?" },
          ],
          hints: ["Offer, don't wait.", "Say what it does and how it stays safe.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "EOD when you're ready.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "One line reports a decision nobody made. Find it.",
          artifact: { kind: "eod", title: "EOD, Tuesday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Matched September's 61 bank lines to the tracker. Three exceptions listed for Dee; nothing changed.\n• Compared three card processors with sources. No savings estimate yet: needs our volume.\n" },
            { text: "• Switched card processing to Option B.\n", flag: "Nobody switched anything. You sent options; Marco decides. The skill turned a comparison into an action.", fix: "• Marco is calling Option A and Option B this week." },
            { text: "• Proposed Monday reminder drafts for overdue accounts. Marco said yes.\n\nTomorrow\n• Set up the Monday drafts.\n• Month-end statements.\n\nWhat Claude helped with\n• The bank match, the fee comparison and the reminder idea. About 2 hours saved (estimate)." },
          ],
          done: "An EOD is a record of what happened. In finance, a wrong 'done' can move money.",
          hints: ["Did anything change today, or was it all reporting?", "Something about the processors.", "The Switched line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Try Tuesday's work for real",
          body: "Run one real reconciliation or research task for your client. Ask for a read-only list of exceptions, or sources on every number, and check every one before it goes anywhere.",
          k: "live-f2",
          label: "I ran a real reconciliation or research task and checked every exception or source.",
          prompts: [
            "Match every line in [bank export] to [invoice tracker]. List every mismatch with both figures side by side. If a line could match two invoices, flag it. Don't change either file.",
            "Compare three [vendors or tools] for [need]. Show rates and fees in a table, link a source for every number, and write not found instead of guessing. Don't estimate our savings.",
          ],
        },
      ],
      done: "Thanks. Good day.",
    },
  ],
}
