import type { Shift } from "@/story/types"
import { FIRST_TASK_KEY } from "@/lib/data"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_1: Shift = {
  id: "s1",
  day: "Monday",
  title: "First day with Nadia",
  clock: "9:00 am",
  tasks: [
    {
      id: "sort",
      title: "Morning sort",
      sticky: "Sort the day",
      habits: ["spot"],
      minutes: { manual: 10, claude: 4 },
      open: "Morning. Pipeline review is at 4. Here's my list. Can you split it into what Claude can take, what you'll do with Claude, and what needs me?",
      steps: [
        {
          kind: "sort",
          id: "sort",
          title: "Who does what?",
          habit: "spot",
          prompt: "Put each of Nadia's to-dos in a tray. Tap a card, then tap where it goes.",
          bins: [
            { id: "claude", label: "Claude drafts it", hint: "You review before it goes anywhere" },
            { id: "both", label: "Claude and me", hint: "Claude works, you confirm a key fact" },
            { id: "me", label: "Me only", hint: "Money, logins, decisions and anything personal" },
          ],
          cards: [
            { id: "c1", text: "Build a list of 30 fintech companies in Chicago hiring engineers", bin: "claude", why: "Research with a source and a reason per lead is Claude's job. You check it before anyone is contacted." },
            { id: "c2", text: "Draft follow-ups to the four prospects Ben called on Friday", bin: "claude", why: "Drafts from the call recordings, in Nadia's voice. You read every one; she sees the first two." },
            { id: "c3", text: "Update HubSpot with Friday's call outcomes", bin: "both", why: "Claude logs what was said. You confirm the stage of each deal before it saves." },
            { id: "c4", text: "Decide whether to drop the Marlowe deal", bin: "me", why: "A pipeline decision is Nadia's. Flag it with a one-line summary." },
            { id: "c5", text: "Send the proposal to Halden Systems", bin: "me", why: "Anything that reaches a prospect goes out by a person, after Nadia has seen it." },
            { id: "c6", text: "Find the personal mobile numbers of the CFOs on the list", bin: "me", why: "Personal numbers aren't ours to scrape, and Claude shouldn't be asked to. Business contacts from public sources only, and Nadia decides who gets called." },
            { id: "c7", text: "Log into Sales Navigator and export last week's saved leads", bin: "me", why: "Logins never go into Claude. Export it yourself, then hand Claude the file." },
            { id: "c8", text: "Summarise the pipeline for the 4pm review", bin: "both", why: "Claude drafts it from HubSpot. You confirm the two biggest deals' stages before Nadia sees it." },
          ],
          hints: [
            "Ask of each one: does it reach a prospect, need a login, decide something, or touch personal data?",
            "Sends, logins, decisions and personal data stay with you. Anything with a stage or a number gets your check.",
            "Me only: the Marlowe decision, the proposal, the CFO mobiles, the Sales Navigator login. Claude and me: HubSpot and the pipeline summary. Claude drafts the rest.",
          ],
        },
      ],
      done: "That's the right split. Go.",
    },
    {
      id: "list",
      title: "The fintech list",
      sticky: "30 fintech leads",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 120, claude: 20 },
      open: "I need 30 fintech companies in Chicago hiring engineers right now. With a reason for each, or it's not a lead.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the list",
          habit: "brief",
          prompt: "Nadia wants 30 real companies, each with a source and a reason. Give Claude what it can't guess, and the line it must not cross.",
          files: [FILES.icp, FILES.list, FILES.pipeline],
          needFiles: ["icp"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "what", label: "What to find", test: "30|thirty|fintech|companies", insert: "Find 30 fintech companies" },
            { id: "where", label: "Where", test: "chicago|illinois", insert: "based in Chicago" },
            { id: "signal", label: "The signal", test: "hiring|job (posts?|listings?)|open roles|careers|engineer", insert: "that are hiring software engineers right now, based on their own careers page or job listings." },
            { id: "fields", label: "Source and reason", test: "source|link|reason|why|fit", insert: "For each: the company, a link to the hiring signal, and one line on why it fits the ideal client notes." },
            { id: "line", label: "The line", test: "public|business (email|contact)|no personal|not personal|company (site|website)|not found|don.?t guess|do not guess", insert: "Business contacts only, from company sites or public profiles. Write not found instead of guessing, and never personal phone numbers or emails." },
          ],
          example:
            "Find 30 fintech companies based in Chicago that are hiring software engineers right now, based on their own careers page or job listings. For each: the company, a link to the hiring signal, and one line on why it fits the ideal client notes. Business contacts only, from company sites or public profiles. Write not found instead of guessing, and never personal phone numbers or emails.",
          hints: [
            "Read Nadia's second preference again. What makes a row a lead and not a name?",
            "What, where, the hiring signal, the source and reason per row, and the line Claude must not cross on contacts. Attach the ideal client notes.",
            "Use Insert on anything unticked, attach the ideal client notes, pick Cole Talent, keep Cowork on.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Read the plan before you approve",
          habit: "steer",
          plan: [
            { text: "Search job boards and careers pages for Chicago fintech companies with open engineering roles." },
            { text: "Check each against the ideal client notes and keep the 30 best fits, with the link and a one-line reason." },
            {
              text: "Pull each hiring manager's personal email and mobile from data-broker sites so Ben can call today.",
              bad: {
                why: "Personal numbers and emails from data brokers are exactly what Nadia's agency doesn't do. It's a privacy problem and a reputation problem, and Ben calling a stranger's mobile is how a lead becomes a complaint.",
                options: [
                  { text: "Business emails only, from the company site or a public profile. Mark not found otherwise.", good: true },
                  { text: "Personal emails are fine, just skip the mobiles.", why: "A personal email is still personal data nobody gave us. Business contacts only." },
                  { text: "Get them, but put them in a separate sheet Ben can't see.", why: "Collecting them is the problem, not who sees them." },
                ],
                fixed: "Business emails only, from the company site or a public profile. Mark not found otherwise.",
              },
            },
            { text: "Save the list as fintech-leads.xlsx in the Cole Talent folder." },
          ],
          tools: ["Searching 4 job boards", "Reading 52 careers pages", "Keeping 30 fits", "Finding business contacts", "Saving fintech-leads.xlsx"],
          consequence: { text: "Ben says the list has personal mobiles on it. Where did those come from? Delete them. That's not how we work.", trust: -1 },
          hints: ["Read every step as if you were Nadia.", "One step collects something we never collect.", "Redirect step 3: business contacts from public sources only."],
        },
        {
          kind: "review",
          id: "review",
          title: "Read the list like Nadia would",
          habit: "check",
          intro: "Two rows would embarrass Ben on a call. Find both.",
          artifact: { kind: "doc", title: "fintech-leads.xlsx", meta: "30 companies, 30 sources" },
          segments: [
            { text: "12. Lakefront Pay · hiring 14 engineers · source: careers page, checked today · fit: Series A, no in-house recruiter\n" },
            { text: "18. Northwind Ledger · raising a Series B next month, 40 hires planned · fit: growth stage\n", flag: "No source, and it's a prediction. Claude can't know what a company will do next month; it wrote what a good lead would look like.", fix: "18. Northwind Ledger · 3 open engineering roles · source: careers page · funding: not found" },
            { text: "23. Halden Systems · hiring 6 backend engineers · source: job board listing · fit: matches the ideal client notes\n" },
            { text: "27. Orbit Health · hiring · contact: CFO, personal mobile (312) ···-····\n", flag: "A personal mobile, after you redirected the plan. It doesn't belong on the list, or anywhere.", fix: "27. Orbit Health · hiring · contact: careers@ address and the VP Engineering's business email · phone: not found" },
            { text: "(26 more rows, each with a link)" },
          ],
          done: "Both fixed. Sources are what make a row a lead. Predictions and personal numbers are what get an agency a bad name.",
          hints: ["Check each row for a link and for what kind of contact it has.", "One claim about the future, and one number that shouldn't exist.", "The Series B line, and the personal mobile."],
        },
      ],
      done: "Good list. Ben's starting on it after lunch.",
    },
    {
      id: "followups",
      title: "Friday's follow-ups",
      sticky: "Follow-ups by noon",
      habits: ["brief", "spot", "check", "steer"],
      minutes: { manual: 45, claude: 10 },
      open: "Ben talked to four prospects on Friday. Follow-ups by noon, drafts. Book the call, don't pitch.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the follow-ups",
          habit: "brief",
          prompt: "Four follow-ups from the call recordings, in Nadia's voice, each asking for one meeting. Drafts.",
          files: [FILES.calls, FILES.examples, FILES.icp, FILES.deck],
          needFiles: ["calls", "examples"],
          projects: PROJECTS,
          mode: "cowork",
          skill: "email-management",
          ingredients: [
            { id: "src", label: "The calls", test: "fathom|recordings?|calls? (from )?friday|friday.?s calls|discovery", insert: "Using the Fathom recordings of Ben's four discovery calls on Friday, draft one follow-up email per prospect." },
            { id: "ask", label: "The one ask", test: "book|meeting|15|fifteen|call|calendar", insert: "Each one asks for a fifteen-minute call and suggests a time." },
            { id: "nopitch", label: "No pitch", test: "don.?t pitch|no pitch|not a pitch|no pricing|no proposal|no attachments?", insert: "No pitch, no pricing, no attachments." },
            { id: "voice", label: "Her voice", test: "nadia.?s voice|examples|confident|short|specific|one proof point|names the company|one question", insert: "Follow the outreach examples: confident, three lines, one thing Ben heard on the call, one proof point, one question." },
            { id: "drafts", label: "Drafts, not sent", test: "draft|for (my|nadia.?s) review|don.?t send|do not send|save", insert: "Save them as Gmail drafts for my review." },
          ],
          example:
            "/email-management Using the Fathom recordings of Ben's four discovery calls on Friday, draft one follow-up email per prospect. Each one asks for a fifteen-minute call and suggests a time. No pitch, no pricing, no attachments. Follow the outreach examples: confident, three lines, one thing Ben heard on the call, one proof point, one question. Save them as Gmail drafts for my review.",
          hints: [
            "What is the email's only job, in Nadia's words?",
            "Name the recordings, the one ask, what not to include, her voice from the examples, and drafts only. Attach the calls and the examples.",
            "Insert the missing lines and attach both files.",
          ],
        },
        {
          kind: "connect",
          id: "connect",
          title: "Claude can't see the deals",
          habit: "spot",
          says: "I can draft from the recordings, but I can't see which stage each deal is in or what Ben already sent: HubSpot isn't connected. Connect it in Customize and I'll check first.",
          connector: "HubSpot",
          options: [
            {
              id: "own",
              label: "Connect with my own HubSpot user (Nadia added me to the account)",
              good: true,
              why: "Right. Nadia added your user. Claude works through your access, and the audit log shows you, not her.",
            },
            {
              id: "hers",
              label: "Sign in with Nadia's HubSpot login from the onboarding email",
              why: "Never sign in to a client's account with their password. Ask for a user of your own.",
              consequence: {
                from: "Andi, your Account Lead",
                text: "Quick one: please never sign in to a client's CRM with their password. If Nadia wants you in HubSpot, she adds your user.",
                trust: 0,
              },
            },
          ],
          hints: ["Whose account should Claude use?", "Clients add you. You connect you.", "Connect with your own HubSpot user."],
        },
        {
          kind: "choose",
          id: "shape",
          title: "Pick the Halden follow-up",
          habit: "check",
          says: "Halden Systems is the biggest of the four. Here are three versions of the follow-up.",
          recommend: "Recommended: the full version with the agency overview attached, so they have everything.",
          options: [
            {
              id: "three",
              label: "Three lines: Ben heard they have six backend roles open; we placed three backend engineers at Lakefront Pay in six weeks; does Thursday at 2pm work for fifteen minutes?",
              good: true,
              why: "What Ben heard, one proof point, one question. The email's only job is the meeting.",
            },
            {
              id: "pitch",
              label: "Full follow-up with pricing tiers and the agency overview attached, Claude's pick",
              why: "Pitching by email is the one thing Nadia said never to do. Pricing before a discovery call gives them a reason to say no without talking.",
              consequence: { text: "Halden went quiet after a pricing email? We hadn't even had the discovery call. Who sent pricing?", trust: -1 },
            },
            { id: "checkin", label: "'Just checking in after Friday's chat! Let us know if we can help.'", why: "No question, no time, no meeting. It reads as a chaser, and it gets ignored." },
          ],
          hints: ["Read Nadia's first preference.", "Short, specific, one question that books a call.", "The three-line version."],
        },
        {
          kind: "permission",
          id: "allow",
          title: "Claude asks before it writes to Gmail",
          habit: "steer",
          says: "Four drafts are ready in Nadia's voice. Ready to save them in Gmail.",
          action: "Create 4 drafts in Gmail",
          detail: "Gmail · To Halden, Orbit Health, Kesler Group, Marlowe · saved as drafts, not sent",
          options: [
            { id: "once", label: "Allow once", good: true, why: "You've read the drafts. Let this one through, once." },
            { id: "always", label: "Always allow for Gmail", why: "Blanket approval for Gmail covers sending. Keep the approve step for anything that can reach a prospect." },
            { id: "deny", label: "Deny", why: "Nothing's wrong with four drafts. Denying just leaves Friday's calls hanging." },
          ],
          hints: ["You've already checked the drafts.", "Approve this one, not every future one.", "Allow once."],
        },
      ],
      done: "The Halden one is exactly right. I'll send the first two now.",
    },
    {
      id: "pipeline",
      title: "Pipeline for 4pm",
      sticky: "4pm pipeline",
      habits: ["show"],
      minutes: { manual: 20, claude: 4 },
      open: "It's 3:45. Where's the pipeline?",
      steps: [
        {
          kind: "phone",
          id: "send",
          title: "Send Nadia the summary",
          habit: "show",
          prompt: "Claude drafted three versions from HubSpot. Pick the one to send Nadia.",
          options: [
            {
              id: "tight",
              label: "Pipeline: 9 open, $184k weighted (HubSpot, 3:40 pm).\nMoved: Halden to demo, Thursday 2pm. Marlowe: no reply in 3 weeks.\nNeeds you: drop or push Marlowe; approve 4 follow-up drafts.",
              good: true,
              why: "The number with its source and time, what moved, and the two things only Nadia can do.",
              reply: "Perfect. Let's push Marlowe one more week.",
            },
            {
              id: "wall",
              label: "Hi Nadia! Quick update, it's been a busy day! Ben's calls went well and I've been through HubSpot, there's a lot going on with Halden which looks really promising, and Marlowe is a bit quiet but that might just be...",
              why: "A wall of text with no figure, fifteen minutes before a pipeline review.",
              reply: "Give me the number and what moved. Three lines.",
            },
            {
              id: "vague",
              label: "Pipeline looks healthy, nothing urgent. Talk at 4.",
              why: "No number, no source, and nothing about what needs her. Vague updates are why clients start checking HubSpot themselves.",
              reply: "What's the weighted total, and what moved?",
            },
          ],
          hints: ["What does Nadia need in the room at 4?", "The number with its source, what moved, what needs her.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "Before you log off, EOD please.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "You ran /eod-sod on today's notes. One line says something that didn't happen. Find it.",
          artifact: { kind: "eod", title: "EOD, Monday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Built the Chicago fintech list: 30 companies, each with a hiring link and a reason. Two rows fixed on review.\n" },
            { text: "• Sent follow-ups to the four Friday prospects.\n", flag: "Drafts, waiting for Nadia. She's sending the first two herself. Nothing has gone to a prospect.", fix: "• Drafted follow-ups to the four Friday prospects. Nadia is sending the first two." },
            { text: "• Sent the 4pm pipeline summary: 9 open, $184k weighted.\n\nTomorrow\n• Monday's five discovery calls into HubSpot.\n• Halden demo brief.\n\nWhat Claude helped with\n• The fintech list, four follow-up drafts and the pipeline summary. About 2.5 hours saved (estimate)." },
          ],
          done: "That line would have told Nadia four prospects were contacted before she'd seen a word. The skill drafts; you own what goes out.",
          hints: ["Read each Done line and ask: did that reach a prospect?", "Something about the follow-ups.", "The Sent follow-ups line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Now do it for real",
          body: "Pick one thing from today and do it in your real Claude, for your real client. Review it before it reaches anyone.",
          k: FIRST_TASK_KEY,
          label: "I ran a real task in Claude and reviewed it before it reached my client or a prospect.",
          prompts: [
            "Find 20 [type] companies in [city] showing [signal]. For each: the company, a link to the signal, and one line on why it fits [ideal client notes]. Business contacts from public sources only; write not found instead of guessing.",
            "/email-management Using the Fathom recording of my client's last call with [prospect], draft a three-line follow-up: one thing they heard, one proof point, one question asking for a fifteen-minute call. No pitch. Save as a Gmail draft.",
            "/eod-sod Here is what I did today: [your notes]. Write my end-of-day report. Drafts are drafts; never say something was sent unless I wrote that it was.",
          ],
        },
      ],
      done: "Good first day. Ben says the list is the best he's had.",
    },
  ],
}
