import type { Shift } from "@/story/types"
import { FILES, PROJECTS } from "./persona"

export const SHIFT_2: Shift = {
  id: "s2",
  day: "Tuesday",
  title: "Calls, research and an idea",
  clock: "9:00 am",
  tasks: [
    {
      id: "calls",
      title: "Calls into HubSpot",
      sticky: "Log the calls",
      habits: ["brief", "steer", "check"],
      minutes: { manual: 50, claude: 12 },
      open: "Can you get Monday's five discovery calls into HubSpot? Next steps and stages, nothing invented.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief Claude on the calls",
          habit: "brief",
          prompt: "Turn five call recordings into HubSpot notes and next steps, without Claude guessing a stage or a number.",
          files: [FILES.calls, FILES.pipeline, FILES.icp],
          needFiles: ["calls"],
          projects: PROJECTS,
          mode: "cowork",
          ingredients: [
            { id: "src", label: "The calls", test: "fathom|recordings?|monday.?s (calls|discovery)|five calls|5 calls|discovery calls", insert: "Use the Fathom recordings of Monday's five discovery calls." },
            { id: "out", label: "What to pull", test: "next steps?|notes?|summary|what was said|outcome", insert: "For each, write a short call note and the next step that was agreed," },
            { id: "who", label: "Owner and date", test: "owner|who|by when|due|date|deadline", insert: "with who owns it and by when." },
            { id: "unsure", label: "When it isn't said", test: "not (said|mentioned|discussed)|unclear|don.?t guess|do not guess|ask nadia|blank|flag|leave the stage", insert: "If a stage, budget or date isn't said on the call, leave it as it is and flag it for Nadia instead of guessing." },
            { id: "place", label: "Where it goes", test: "hubspot|crm|deal record", insert: "Log them on each deal in HubSpot." },
          ],
          example:
            "Use the Fathom recordings of Monday's five discovery calls. For each, write a short call note and the next step that was agreed, with who owns it and by when. If a stage, budget or date isn't said on the call, leave it as it is and flag it for Nadia instead of guessing. Log them on each deal in HubSpot.",
          hints: [
            "Where do call notes usually go wrong? Stages and budgets nobody said.",
            "Name the recordings, ask for notes and next steps with owners and dates, say what to do when something isn't said, say where it goes.",
            "Insert the missing lines and attach the recordings.",
          ],
        },
        {
          kind: "plan",
          id: "plan",
          title: "Check what it changes",
          habit: "steer",
          plan: [
            { text: "Pull the five transcripts from Fathom." },
            { text: "Write a call note and the agreed next step for each deal, with owner and date." },
            {
              text: "Move every deal to the Proposal stage, since we've now had a discovery call with each.",
              bad: {
                why: "A stage is what happened on the call, not what comes next in the funnel. Marlowe said they're pausing hiring; moving them to Proposal makes the pipeline lie.",
                options: [
                  { text: "Set each stage from what was said on the call; leave it and flag it when unclear.", good: true },
                  { text: "Move them all to Proposal but add a note.", why: "The weighted pipeline number reads the stage, not the note. Wrong stage, wrong forecast." },
                  { text: "Leave every stage where it is.", why: "Two deals really did move. Log what happened; don't freeze the pipeline." },
                ],
                fixed: "Set each stage from what was said on the call; leave it and flag it when unclear.",
              },
            },
            { text: "Log the notes and next steps on each deal in HubSpot and list what was flagged." },
          ],
          tools: ["Reading 5 transcripts (2 h 10 min)", "Writing 5 call notes", "Setting 2 stages, flagging 1", "Logging to HubSpot", "Listing 3 flags"],
          consequence: { text: "Why is Marlowe in Proposal? They told Ben they're pausing hiring until Q1. My forecast is now wrong.", trust: -1 },
          hints: ["Which step decides something the calls didn't?", "One step moves every deal the same way.", "Redirect step 3: stages from the calls only."],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the notes it wrote",
          habit: "check",
          intro: "Two of these would mislead the team. Find both.",
          artifact: { kind: "tasks", title: "5 deals updated in HubSpot", meta: "From: Monday's discovery calls" },
          segments: [
            { text: "Kesler Group · stage: Discovery → Proposal · next: Ben sends proposal by Friday\n" },
            { text: "Orbit Health · stage: Discovery · next: second call, date not set · budget confirmed: $60,000\n", flag: "Nobody said $60,000 on the call. It's the 'typical deal size' from the ideal client notes, written up as a confirmed budget.", fix: "Orbit Health · budget: not discussed. Ask Nadia." },
            { text: "Marlowe · stage: Discovery, unchanged · note: pausing hiring until Q1 · next: Nadia to decide\n" },
            { text: "Halden Systems · stage: Discovery → Demo · next: demo Thursday 2pm, Ben\n" },
            { text: "Halden Systems · stage: Discovery → Demo · next: demo Thursday 2pm, Ben\n", flag: "The same deal twice. A duplicate in HubSpot double-counts the forecast.", fix: "Delete the duplicate." },
            { text: "Lakefront Pay · stage: Discovery · next: Ben to send two candidate profiles by Wednesday" },
          ],
          done: "Transcripts are where Claude shines. Budgets and stages are where it fills gaps, so check those two every time.",
          hints: ["Compare each line with what could actually have been said.", "One number nobody said, one line you've seen before.", "The $60,000 budget, and the second Halden line."],
        },
      ],
      done: "HubSpot looks right. Thanks for flagging Marlowe instead of moving it.",
    },
    {
      id: "research",
      title: "Halden demo brief",
      sticky: "Brief on Halden",
      habits: ["brief", "check"],
      minutes: { manual: 60, claude: 15 },
      open: "Halden's demo is Thursday. Brief me on them, one page, nothing I'd be embarrassed to repeat.",
      steps: [
        {
          kind: "brief",
          id: "brief",
          title: "Brief the research",
          habit: "brief",
          prompt: "Get Nadia one page on Halden Systems she can trust in the room.",
          files: [FILES.icp, FILES.pipeline],
          needFiles: [],
          projects: PROJECTS,
          mode: "any",
          ingredients: [
            { id: "what", label: "Who", test: "halden", insert: "Write a one-page brief on Halden Systems" },
            { id: "recent", label: "What's recent", test: "news|recent|last (six|6) months|announce|funding|launch", insert: "covering what they do, anything announced in the last six months, and their open engineering roles." },
            { id: "people", label: "Who we'll meet", test: "who|leadership|founder|cto|vp|decision.?maker|team", insert: "Name the leadership from their own site or public profiles." },
            { id: "shape", label: "The shape", test: "one page|short|bullets|headings", insert: "Short, with headings." },
            { id: "sources", label: "Sources, or not found", test: "source|link|cite|not found|don.?t know|unsure|say so|instead of guessing|only what you can link", insert: "Link a source for every claim, write not found instead of guessing, and don't tell me what they're thinking." },
          ],
          example:
            "Write a one-page brief on Halden Systems covering what they do, anything announced in the last six months, and their open engineering roles. Name the leadership from their own site or public profiles. Short, with headings. Link a source for every claim, write not found instead of guessing, and don't tell me what they're thinking.",
          hints: [
            "A company brief is where Claude most often sounds sure and is wrong. What protects you?",
            "Ask for sources, permission to say not found, and no mind-reading.",
            "Insert the missing lines. Chat or Cowork both work for web research.",
          ],
        },
        {
          kind: "review",
          id: "review",
          title: "Check the brief",
          habit: "check",
          intro: "Two claims would embarrass Nadia on Thursday. Find both.",
          artifact: { kind: "doc", title: "Halden Systems, brief", meta: "1 page, 6 sources" },
          segments: [
            { text: "What they do: payments infrastructure for mid-size lenders · source: company site\nRecent: opened a second office in Chicago in June · source: press release\nOpen roles: 6 backend engineers, 2 platform engineers · source: careers page\n\nLeadership\n" },
            { text: "VP Engineering Sam Ortiz joined in March from a large bank.\n", flag: "No source, and a specific name and date. If the VP is called something else, Nadia looks careless in front of the person she's pitching.", fix: "Leadership: see the team page (link). VP Engineering: not verified." },
            { text: "CEO and founder: listed on the team page (link).\n\nWhat to know\n" },
            { text: "They're unhappy with their current recruiter and looking to switch.", flag: "Nobody can know that from public sources. It's what Claude thinks Nadia wants to hear.", fix: "Current recruiter: unknown. Ask on the call." },
          ],
          done: "Ask for sources and permission to say not found, then check anything that names a person or reads their mind.",
          hints: ["Which claims have no link?", "A name nobody sourced, and a feeling nobody could know.", "The Sam Ortiz line, and the unhappy-with-their-recruiter line."],
        },
      ],
      done: "Good. I'll ask about the recruiter on the call instead of assuming.",
    },
    {
      id: "idea",
      title: "A proactive idea",
      sticky: "Suggest a workflow",
      habits: ["steer", "show"],
      minutes: { manual: 15, claude: 5 },
      open: "Leads go cold because nobody sends the third email. Every time.",
      steps: [
        {
          kind: "choose",
          id: "shape",
          title: "Pick the right shape",
          habit: "steer",
          says: "I can help with third-touch follow-ups in four ways. Which fits Nadia?",
          options: [
            {
              id: "sched",
              label: "Scheduled task: Mondays and Thursdays at 8:00 am Chicago, find deals with no reply in 5+ days and draft a third touch for each, saved for review",
              good: true,
              why: "Same job, twice a week, and drafts only, so nothing reaches a prospect unread.",
            },
            { id: "seq", label: "An automated sequence that sends touches two and three on a timer", why: "Emails to prospects with nobody reading them first. One goes to someone mid-negotiation and the deal is gone." },
            { id: "adhoc", label: "Ask me each time you notice a deal has gone quiet", why: "That depends on noticing, which is the exact problem Nadia just described." },
            { id: "project", label: "A Claude Project with the outreach examples", why: "Useful context, but someone still has to start it. Pair it with a schedule." },
          ],
          hints: ["What has to happen without anyone remembering?", "A fixed time, and nothing sent unread.", "The scheduled task that saves drafts."],
        },
        {
          kind: "phone",
          id: "offer",
          title: "Offer it to Nadia",
          habit: "show",
          prompt: "Tell Nadia what you can set up.",
          options: [
            {
              id: "offer",
              label: "Idea: Monday and Thursday mornings, Claude finds every deal quiet for 5+ days and drafts a third touch. You or Ben review and send. Want me to set it up?",
              good: true,
              why: "Proactive means offering the fix, and saying how it stays safe.",
              reply: "Yes. That's the one that's been killing us.",
            },
            {
              id: "bot",
              label: "I set up a sequence that emails quiet prospects automatically.",
              why: "It emails prospects unread, and you didn't ask her first.",
              reply: "Without me seeing them? Turn it off, now.",
            },
            { id: "later", label: "Let me know if you ever want help with that.", why: "Waiting to be asked isn't proactive. Offer the fix.", reply: "Sure. Any ideas?" },
          ],
          hints: ["Offer, don't wait.", "Say what it does and how it stays safe.", "The first one."],
        },
      ],
    },
    {
      id: "eod",
      title: "End of day",
      sticky: "EOD report",
      habits: ["check", "show"],
      minutes: { manual: 20, claude: 5 },
      open: "EOD when you're ready.",
      steps: [
        {
          kind: "review",
          id: "eod",
          title: "Check your EOD before it goes",
          habit: "check",
          intro: "One line reports something that hasn't happened. Find it.",
          artifact: { kind: "eod", title: "EOD, Tuesday", meta: "Drafted by /eod-sod" },
          segments: [
            { text: "Done today\n• Logged Monday's five discovery calls in HubSpot: notes, next steps, two stage changes. Orbit's budget and Marlowe flagged for Nadia.\n• One-page Halden brief with sources for Thursday.\n" },
            { text: "• Booked second calls with Orbit Health and Kesler.\n", flag: "Nobody booked anything. The next steps are logged; Nadia and Ben confirm them. The skill turned 'next step' into 'done'.", fix: "• Next steps logged; Orbit and Kesler calls need Nadia's confirmation." },
            { text: "• Proposed twice-weekly third-touch drafts. Nadia said yes.\n\nTomorrow\n• Set up the Monday and Thursday drafts.\n• The forty-prospect campaign.\n\nWhat Claude helped with\n• Call notes, the Halden brief and the follow-up idea. About 2 hours saved (estimate)." },
          ],
          done: "An EOD is a promise about what happened. Keep it exact, especially about meetings.",
          hints: ["Did you book anything today?", "Something about second calls.", "The Booked line."],
        },
        {
          kind: "live",
          id: "live",
          title: "Try Tuesday's work for real",
          body: "Run one real call-notes or research task for your client. Ask for stages and next steps from the call only, or sources on every claim, and check every one before it goes anywhere.",
          k: "live-l2",
          label: "I ran a real call-notes or research task and checked every stage, number and source.",
          prompts: [
            "Use the Fathom recording of my client's last call with [prospect]. Write a call note and the agreed next step with owner and date. If a stage, budget or date wasn't said, leave it and flag it. Log it on the deal in HubSpot.",
            "Write a one-page brief on [company] for a call on [date]: what they do, recent announcements, open roles, leadership from their own site. Link a source for every claim and write not found instead of guessing.",
          ],
        },
      ],
      done: "Thanks. Good day.",
    },
  ],
}
